### ISSUE TITLE
Vizy saves project config data differently between save field and project-config/rebuild methods

### ISSUE THREAD

**Issue by BenParizek** [verbb/vizy#102]
I've got a nice, arcane bug for you. I posted it over in the Craft CMS Issues first, so please see this thread for details and let me know if you have any follow up questions:

https://github.com/craftcms/cms/issues/10512#issuecomment-1035662317

**Comment by mattbloomfield** [comment]
👍🏼

**Comment by engram-design** [comment]
Cheers @BenParizek going to dive into this shortly.

**Comment by engram-design** [comment]
@BenParizek Just left my comments https://github.com/craftcms/cms/issues/10512
