### ISSUE TITLE
Editor breaks when trying to drag a block in another block

### ISSUE THREAD

**Issue by AxelStorm13** [verbb/vizy#103]
**Description**
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/54795137/154697861-6e3810e0-82ec-4334-bfa3-9501e594957a.png">

**Steps to reproduce**
![vizy](https://user-images.githubusercontent.com/54795137/154702760-51c2cdb8-b624-4109-bb16-be3f0149d3c7.gif)

**Additional info**
- Plugin version: 1.0.9
- Craft version: 3.7.29
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
A known issue I'm afraid, I'm trying to scrub up on my ProseMirror knowledge to prevent this behaviour, as it shouldn't be possible (you could drag a block to another block that doesn't support the same type, etc.

Will get on this ASAP.

**Comment by engram-design** [comment]
Fixed in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0)
