### ISSUE TITLE
Undefined index error when saving entry with a Vizy field

### ISSUE THREAD

**Issue by ryguy2407** [verbb/vizy#104]
I made some changes on my local environment to my vizy field and checked that it was working locally (which is is). I then pushed the changes to production and applied the project config. The changes are applied as expected but when I save an entry with the updated field I get the following error:

Undefined index: type
 in /var/www/vhosts/newwordorder.com.au/httpdocs/vendor/verbb/vizy/src/helpers/Matrix.php at line 29

I've attached a screenshot of the error as well.

**Steps to reproduce**
1. Change Vizy field locally (in this case I added a new tab and field to the layout of a block that already exists, the field already existed as well I was just adding it to the block).
2. Push changes to production and apply project config
3. Attempt to save any entry that uses vizy fields causes the index not found error.

**Additional info**
- Plugin version: dev-craft-3 as 1.0.3
- Craft version: 3.7.31
- Multi-site: No

**Additional context**
![screencapture-newwordorder-au-nwoadmin-entries-contact-21297-contact-2022-02-23-12_05_36](https://user-images.githubusercontent.com/5257196/155250585-1d30c3f3-1576-4081-8ebf-53f4726c0245.png)

**Comment by ryguy2407** [comment]
Just as a sanity check I ran all the craft updates locally and pushed to production and I still get the same error when saving any entries that use a vizy field. Any elements that don't have vizy fields save fine.

On my local setup (using Nitro) I can save elements that have vizy fields. Perhaps I should nuke the vendor folder on production and reinstall everything?

Now running Craft 3.7.34

**Comment by ryguy2407** [comment]
So sorry, I'm such an idiot, I realised that the version I was running was a dev version, I'm not actually sure how that happened, I only run the updates as required but I must've pulled in this version at some stage. After updating to 1.0.9 it all works as expected. Apologies!

**Comment by engram-design** [comment]
Ah, yep sorry about that - still working through some saving issues in `craft-3` branch!
