### ISSUE TITLE
Allow emojis in main rich text section

### ISSUE THREAD

**Issue by sjcallender** [verbb/vizy#105]
### What are you trying to do?

I would like to be able to include emojis in the rich text section of a Vizy field as shown below.

![image](https://user-images.githubusercontent.com/984311/155334113-10e70459-f623-4ddb-855d-4c3bcb0e4b06.png)

### What's your proposed solution?

@engram-design works some majik and makes it possible?

### Additional context

You're our favorite person.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-3 as 1.0.9",
  "...": "..."
}
```

Then run `composer update`.

**Comment by sjcallender** [comment]
Awesome. Thanks, Josh.

**Comment by engram-design** [comment]
Added in [1.0.10](https://github.com/verbb/vizy/releases/tag/1.0.10)
