### ISSUE TITLE
(Per-)Block type count limits 

### ISSUE THREAD

**Issue by yoannisj** [verbb/vizy#112]
**What are you trying to do?**
I often need to limit how many types a specific block can be used by content editors. Neo allows this, and I find it one of its neatest features. Here are a couple of use-cases I encountered in the past:

- Editors can add up to X components (e.g. max 3 physical addresses)
- Editors need to choose one single component out of a list of supported components (e.g. a Link/Button vs a Form)
- Editors can choose to include and position a computed component (e.g. a grid with related entries based on a field defined on the entries and not the owner element), and that component can only be included once
- If the computed component is required, then adding a `minBlocks = 1` setting makes that possible easily (without custom validation rules registed in a module for example).

Vizy comes with other great features which offer better editor experience for modular content, and makes it a potential alternative to all of Neo, Matrix, Super-Table and Redactor fields. However, this feature from Neo would be greatly missed in both those cases.

**What's your proposed solution?**
Add a `minBlocks` and `maxBlocks` setting for block types. Another great addition would be to allow a twig expression in these settings, so it can react to the field's context (e.g. the owner element).

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0)
