### ISSUE TITLE
GraphQL not working correctly

### ISSUE THREAD

**Issue by aodihis** [verbb/vizy#113]
**Description**
When fetching entry or anything  after installing vizy plugin I got this kind of errors :

`"verbb\\vizy\\fields\\VizyField::getContentGqlType(): Return value must be of type array, verbb\\vizy\\gql\\types\\NodeCollectionType returned"`

**Additional info**
- Plugin version: 2.0.0-beta.1
- Craft version: 4.0.0-beta.3
- Multi-site: Yes or No

**Comment by engram-design** [comment]
Should be fixed in [2.0.0-beta.2](https://github.com/verbb/vizy/releases/tag/2.0.0-beta.2)
