### ISSUE TITLE
Weird &amp; behaviour

### ISSUE THREAD

**Issue by bavocorteville** [verbb/vizy#115]
**Description**

I have no idea what causes it, but there are occasional issues with `&amp;` in Vizy fields. 

![image](https://user-images.githubusercontent.com/2085698/161482193-db846f29-66da-4985-b00a-01854ab9c8da.png)
![image](https://user-images.githubusercontent.com/2085698/161483371-67400585-8e4c-4e6a-b4d8-e01f22d47630.png)

**Additional info**
- Plugin version: 1.0.12
- Craft version: 3.7.37
- Multi-site: Yes

**Additional context**

I know it's hard to fix something you don't know how to trigger. Some actions that I've runned: resave entries, adding new sites ...)

**Comment by engram-design** [comment]
People have certainly mentioned this in the past, I just have struggled to replicate it! If you remove all the `&amp;` instances and resave, does that do anything still? Is it a result of just using `&` in text?

**Comment by bavocorteville** [comment]
Not even sure it is an `&amp;` issue. The text in my second screenshot doesn't contain an ampersand. In the code view of that field you can see `&nbps;` where the problem occurred before.
When I fix the text and resave, the problem does not occur. 

![image](https://user-images.githubusercontent.com/2085698/161497788-1f46f1bb-2979-4721-bf53-c94326fab9f4.png)

**Comment by engram-design** [comment]
Hmmm, do you know if this text was pasted in from somewhere, or written directly? Will do my best to replicate it, but let me know if there's anything that consistently does this.

**Comment by anchovy** [comment]
I'm having exactly the same issue - typed, not pasted.
If I write 'Media Kit & Booking Forms' - and preview it's perfect, as expected.
![Screenshot 2022-04-05 at 2 17 35 PM](https://user-images.githubusercontent.com/599005/161666224-551bb8e3-730e-43ae-bd73-21a97f860c46.png)


But as soon as I save the entry and come back it's now 'Media Kit &amp; Booking Forms'
![Screenshot 2022-04-05 at 2 18 15 PM](https://user-images.githubusercontent.com/599005/161666236-99cf78ad-5686-48a7-8360-d20ee29cc8b2.png)



PHP version | 8.0.9
Craft edition & version | Craft Pro 3.7.37
Vizy | 1.0.12
Multi-site| No

**Comment by engram-design** [comment]
I can't replicate that sorry (one of the first thing I've tried obviously!). What browser are you using, just in case that's a difference?

Can you send through your raw JSON from your content database table for the entry?

**Comment by anchovy** [comment]
Hi @engram-design - it's not browser dependent; occuring in chrome (latest), brave, safari etc....

```
INSERT INTO `stc_pagecontent` (`elementId`, `siteId`, `dateCreated`, `dateUpdated`, `uid`, `field_pageContentRow`, `field_rowBackgroundColour`)
VALUES
	(32956, 1, '2022-03-01 21:22:52', '2022-04-05 02:17:49', 'eedbd1ac-2dc5-4c32-837d-c1ea1822b68b', '[{\"type\":\"heading\",\"attrs\":{\"textAlign\":\"start\",\"level\":2},\"content\":[{\"type\":\"text\",\"text\":\"Media Kit &amp;amp; Booking Forms\"}]},{\"type\":\"vizyBlock\",\"attrs\":{\"id\":\"vizy-block-3M7n0Dbr63\",\"enabled\":true,\"collapsed\":false,\"values\":{\"type\":\"type-c5SMDMikS6\",\"content\":{\"fields\":{\"vizyColumn1\":[{\"type\":\"vizyBlock\",\"attrs\":{\"id\":\"vizy-block-a0V8VuVUht\",\"enabled\":true,\"collapsed\":false,\"values\":{\"type\":\"type-sC2TtrHf2X\",\"content\":{\"fields\":{\"pdfDownload\":{\"ariaLabel\":null,\"customQuery\":null,\"customText\":\"???? Media Kit\",\"target\":null,\"title\":null,\"type\":\"asset\",\"value\":\"37413\"}}}}}},{\"type\":\"vizyBlock\",\"attrs\":{\"id\":\"vizy-block-bVmkhbwhEO\",\"enabled\":true,\"collapsed\":false,\"values\":{\"type\":\"type-sC2TtrHf2X\",\"content\":{\"fields\":{\"pdfDownload\":{\"ariaLabel\":null,\"customQuery\":null,\"customText\":\"The NZ Dental Journal (NZDJ)\",\"target\":null,\"title\":null,\"type\":\"asset\",\"value\":\"31181\"}}}}}},{\"type\":\"vizyBlock\",\"attrs\":{\"id\":\"vizy-block-SRcBnhjPGQ\",\"enabled\":true,\"collapsed\":false,\"values\":{\"type\":\"type-sC2TtrHf2X\",\"content\":{\"fields\":{\"pdfDownload\":{\"ariaLabel\":null,\"customQuery\":null,\"customText\":\"Professional Development Guide\",\"target\":null,\"title\":null,\"type\":\"asset\",\"value\":\"37455\"}}}}}}],\"vizyColumn2\":[{\"type\":\"vizyBlock\",\"attrs\":{\"id\":\"vizy-block-GEuO80rycp\",\"enabled\":true,\"collapsed\":false,\"values\":{\"type\":\"type-0ZkDOMRk9E\",\"content\":{\"fields\":{\"pdfDownload\":{\"ariaLabel\":null,\"customQuery\":null,\"customText\":\"???? News\",\"target\":null,\"title\":null,\"type\":\"asset\",\"value\":\"31178\"}}}}}},{\"type\":\"vizyBlock\",\"attrs\":{\"id\":\"vizy-block-JJ2fNNQYKh\",\"enabled\":true,\"collapsed\":false,\"values\":{\"type\":\"type-0ZkDOMRk9E\",\"content\":{\"fields\":{\"pdfDownload\":{\"ariaLabel\":null,\"customQuery\":null,\"customText\":\"Annual Report\",\"target\":null,\"title\":null,\"type\":\"asset\",\"value\":\"31170\"}}}}}}]}}}}}]', '{\"label\":\"Light Teal\",\"color\":[{\"color\":\"#e6f3f0\",\"class\":\"secondary-light\"}]}');
```

Data is above what you are after hopefully.
NB - this also happens saving via the save button or hitting [⌘] + S

**Comment by engram-design** [comment]
Thanks for that, but super-strange. If I change that back to a normal `&` and re-save, it's all back to normal. But it's certainly saving in your database incorrectly `Media Kit &amp;amp; Booking Forms`. I'll keep trying to get to the bottom of it.

**Comment by bavocorteville** [comment]
> Hmmm, do you know if this text was pasted in from somewhere, or written directly? Will do my best to replicate it, but let me know if there's anything that consistently does this.

In our case the client is copy pasting their text from Word.

**Comment by engram-design** [comment]
@bavodeclercq Would love to get an example via email if that's possible? `support at verbb.io`.

**Comment by engram-design** [comment]
@anchovy Just wanted to check the OS you were using, just in case that matters? It also looks like the field is within a Super Table field?

**Comment by adrienpicard** [comment]
Just faced this issue upgrading from Vizy `1.0.9` to `1.0.13`.

Whenever I use `&` in a Vizy field, it is saved as `&amp;` in the database. Rolling back version, it looks like this was introduced in `1.0.11`. I rolled back to `1.0.10` in the meantime, it works as expected.

**Comment by engram-design** [comment]
@adrienpicard Still unable to reproduce this. Wondering if you can answer:
- Is your site multi-site? If so, what language are you adding content as?
- Is this when you paste or write `&` words?
- Is this in the WYSIWYG portion of the field, or in a Vizy block field?
- What browser and OS are you on?
- What buttons do you have enabled for the field?

I should mention that is should be encoded in the database (`some text &amp; more text`) and decoded when rendering in the field, or in your templates `some text & more text`

**Comment by engram-design** [comment]
Actually, think I might've finally been able to reproduce this in a multi-site scenario. I know you've back-tracked to 1.0.10 @adrienpicard but if anyone else needs to get this early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-3 as 1.0.13",
  "...": "..."
}
```

Then run `composer update`.

**Comment by adrienpicard** [comment]
Thanks @engram-design . Unfortunately it still happens on `dev-craft-3`. Answers below, I hope it helps!

- Site is not multi-site
- It happens when I write `&` and when I paste it in the WYSIWYG section (I haven't tried in a block)
- I'm using Chrome 100 on macOS 12.3.1
- This is my field config:

```
{
 "buttons": ["formatting", "bold", "link", "align-left", "align-right", "clear-format", "undo", "redo"],
  "formatting": ["h2", "blockquote"],
  "toolbarFixed": true
}
```

**Comment by engram-design** [comment]
Thanks for that, still no further progress - how frustrating! I noticed some weird (different) behaviour to when I made changed to a draft then saved. Wondering if you can try to compare your results?

1. Open up an entry with a Vizy field. Ensure that there's no active drafts or unsaved changes.
2. Write a string containing `&` and observe Craft saving that content as a draft. The little spinner near the entry title should show a tick and a blue vertical line should appear on the left-hand side of the editor.
3. Refresh the page - is that still an `&` or `&amp;`?
4. If it is, you can stop here, if not, save the entry and refresh the page - does that change?

Thanks!

**Comment by adrienpicard** [comment]
Something that I should have mentioned actually sorry @engram-design. When editing, the `&` is displayed correctly in the CP / the WYSIWYG. 

For me it's on the frontend that I noticed a change. Using `1.0.10` the `&amp;` is decoded in the output, but it's not past that version. I'm using the `renderHtml` method on the node.

**Comment by engram-design** [comment]
Ah, thanks for the clarification, although no change on my end, as its rendering `&amp` in the HTML source (correctly), which shows up as a `&`.

Are you able to look up the row in the `content` db table and send through the value for the column that matches the field?

**Comment by adrienpicard** [comment]
So it gets encoded (as it should) from `1.0.11` basically. I just thought it was getting decoded through `renderHtml`.

`1.0.10`
`[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Text and & more text"}]}]`

`1.0.11` 
`[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Text and &amp; more text"}]}]`

**Comment by engram-design** [comment]
Yeah that looks correct, but it won't be decoded, changing it back from `&amp;` to `&`, but it shouldn't matter as rendering `&amp;` in HTML is valid as visually that should show `&`. 

The reason for the lack of decoding it to prevent XSS attacks, where you could save `<script>alert(1)</script>` as the content of the field, it get's encoded in the database, and if you decode it back when rendering it'll execute that.

**Comment by adrienpicard** [comment]
Makes total sense, thanks for your help @engram-design.

**Comment by engram-design** [comment]
Closing for now, please let me know if there's any further ongoing issues with this, but it _should_ be fixed in for both Craft 3 and Craft 4 versions.
