### ISSUE TITLE
Documentation on the GraphQL API

### ISSUE THREAD

**Issue by tremby** [verbb/vizy#119]
**What are you trying to do?**

Figure out which field does what.

**What's your proposed solution?**

Add documentation on the GQL API, such that it shows up in Graphiql, like Craft's built-in GQL bits.

**Comment by engram-design** [comment]
Added proper descriptions to attributes for the next release. To get this early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-3 as 1.0.12",
  "...": "..."
}
```

Then run `composer update`.
