### ISSUE TITLE
BUG: Most formatting buttons do not work on nested Redactor fields

### ISSUE THREAD

**Issue by adrienne** [verbb/vizy#12]
**Description**

If i have a Redactor field inside a Vizy block, some buttons work but others (notably bold and italic; I'm not sure about any others) completely fail to work. Instead they highlight the entire Vizy field including all blocks. Other buttons, such as link insertion, won't work for highlighted text (again the entire Vizy field is selected) although they will insert a link, they'll just do it in the wrong place and without the highlighted text.

**Steps to reproduce**
1. Create a block in Vizy with a Redactor field inside (ensuring that you're using a Redactor config with bold and italic)
2. Make an entry using that block, highlight some text inside the block, and try to Bold or Italicize it. Also try adding a link.

**Additional info**
- Plugin version: dev-3 as 1.0.0
- Craft version: 3.6

**Comment by adrienne** [comment]
@engram-design just making sure you see this ASAP because i suspect it'll be a show-stopper for a lot of us.

**Comment by engram-design** [comment]
Looks like there's some serious incompatibility issues with Redactor, and looking into what we can do.

**Comment by theskyfloor** [comment]
Recommended solution? Using only Vizy fields for WYSIWYG or maybe CKEditor? Thanks for the top notch bug fixes as always!

**Comment by engram-design** [comment]
@theskyfloor For the moment, using nested Vizy is the workaround, but hopefully I can figure out something to handle Redactor.

**Comment by theskyfloor** [comment]
Cool, just curious, I don't like Redactor anyway : P

**Comment by adrienne** [comment]
@engram-design - nested Vizy fails too, though, if you're trying to edit on mobile. https://github.com/verbb/vizy/issues/17

**Comment by engram-design** [comment]
FYI, still working on this, but after oodles of different scenarios, Redactor just doesn't want to play ball. My only real option left is to swap out the jQuery-based plugin and use one [Vue-compatible](https://github.com/imperavi/vue-redactor)

**Comment by nfq** [comment]
@engram-design what's the latest on this? Basically, selecting text in nested Redactor, Vizy or CKEditor fields doesn't work, hence the formatting button issue. We're using this on a big project that is due to go live next week, so we're pretty concerned and can't hand-over to the client with the Editor not working properly. Any ETA?

**Comment by engram-design** [comment]
What's the issue with selecting text in nested Vizy fields?

I still haven't been able to figure out the issue with Redactor, but working on it. I'm going to need to see if I can access their source, as it's something in their handling of things that just doesn't play right with Vue/Tiptap/Prosemirror/Vizy.

Using CKEditor on the other hand is pretty flawless.

**Comment by nfq** [comment]
Hey Josh,

If I use CMD + a, I can select all text and it's highlighted. But I can't select single words by double clicking on a word. Same in Redactor and CKEditor.

**Comment by engram-design** [comment]
@nfq Looks like this is another issue with Firefox and Safari (Chrome and Edge work as expected). Will look into it shortly.

**Comment by engram-design** [comment]
Happy to say Redactor should be **finally** working in [1.0.8](https://github.com/verbb/vizy/releases/tag/1.0.8).

**Comment by nfq** [comment]
Awesome!
