### ISSUE TITLE
[Craft 4.x]: Required field not respected

### ISSUE THREAD

**Issue by JeanLucEsser** [verbb/vizy#122]
**Description**

Enabled entry can be saved even with the field is empty and required.

**Steps to reproduce**
1. Create a Vizy field (by default, no configuration, no groups)
2. Add it to a section layout and set it as required
3. Create an entry, enable it, leave the field empty and save it

**Additional info**
- Plugin version: latest
- Craft version: 4, latest beta
- Multi-site: No

**Comment by engram-design** [comment]
Fixed in [1.0.13](https://github.com/verbb/vizy/releases/tag/1.0.13) and  [2.0.0-beta.3](https://github.com/verbb/vizy/releases/tag/2.0.0-beta.3)
