### ISSUE TITLE
Issues adding/using a block with no fields

### ISSUE THREAD

**Issue by tremby** [verbb/vizy#123]
**Description**

I want to make some custom content blocks which represent particular widgets. Some of these have no customization at all, and so it doesn't make sense to add any fields to them. But when I make such a widget I see various bugs.

**Steps to reproduce**

1. If I save a widget with no fields, it does not appear on the list of available blocks when editing an entry.
2. If I add a tab but add no field to that tab, and I save, then go in to the edit field page again, the tab I added is gone
3. If I add a tab, and add a field (or UI element) to that tab, it then saves properly and I can then add this block to a page. But if I then edit the Vizy again to delete the tab (and UI element) and save, it has not deleted, it's still there if I look and edit again.

**Additional info**
- Plugin version: craft-4 at 16eea67
- Craft version: 4.0.x-dev at 6e466a0
- Multi-site: Yes

**Additional context**
- Headless mode

**Comment by engram-design** [comment]
That's correct behaviour for the moment, because we use Craft's field layouts. Fields are required for a Vizy block, so you won't be able to save the field unless you add some fields to the field layout.

Secondly, Craft's field layout won't allow you to save any tabs that have no fields. Try saving a section with a blank tab.

And the reason for it not deleting it as per the above, that you **must** have a field in there.

What I might recommend is to either use a UI element (and use CSS to hide it), or create a custom UI element for a blank field, that you can use as a placeholder. We've done a similar thing with Neo, which suffers the same issue.

```
use module\fieldlayoutelements\Spacer;
use craft\events\DefineFieldLayoutElementsEvent;
use craft\models\FieldLayout;
use yii\base\Event;

Event::on(FieldLayout::class, FieldLayout::EVENT_DEFINE_UI_ELEMENTS, function(DefineFieldLayoutElementsEvent $event) {
    $event->elements[] = Spacer::class;
});
```

```
<?php
namespace module\fieldlayoutelements;

use Craft;
use craft\base\ElementInterface;
use craft\fieldlayoutelements\BaseUiElement;
use craft\helpers\Cp;
use craft\helpers\Html;

class Spacer extends BaseUiElement
{
    // Protected Methods
    // =========================================================================

    protected function selectorLabel(): string
    {
        return Craft::t('app', 'Spacer');
    }


    // Public Methods
    // =========================================================================

    public function settingsHtml()
    {
        return Cp::textFieldHtml([
            'label' => Craft::t('app', 'Spacer'),
            'id' => 'spacer',
            'name' => 'spacer',
        ]);
    }

    public function formHtml(ElementInterface $element = null, bool $static = false)
    {
        return '';
    }
}
```

**Comment by tremby** [comment]
OK. Putting in a "heading" or "tip" or "warning" UI element will be fine, and probably not a bad idea anyway. But might it be possible to have some UI messages clearing up the confusion of someone like me who tries to do this?

**Comment by engram-design** [comment]
I'll see what I can do! For now, I've added some instruction text to clarify.
