### ISSUE TITLE
Nest a Vizy field within another of the same type

### ISSUE THREAD

**Issue by tremby** [verbb/vizy#125]
**What are you trying to do?**

I want to define some "layout"-centric blocks. For example, a "two columns" block would have two wysiwygs in it, and once it hits the front end they'd display side by side.

**What's your proposed solution?**

I'd ideally need to be able to nest a Vizy field within another Vizy field of the same definition.

**Additional context**

I'm aware I can nest a Vizy within a Vizy of a *different* definition. I might be able to get away with this but it'll mean duplicating a lot of configuration if I want all the same block types to be available within the nested one (which I likely will). Is not allowing the same type to be nested a technical limitation?

**Comment by engram-design** [comment]
I'll say that we do have "layout" type blocks, or a concept planned, but haven't worked out the finer details yet. See https://github.com/verbb/vizy/issues/72

So yeah, this is one of those things that would add a pretty massive amount of complexity unfortunately, and is a bit of a technical limitation. I don't have any plans to support this in the immediate future (lots more to do!), but appreciate you're not the first to ask about this.

**Comment by tremby** [comment]
Oh, nice. I look forward to seeing what that'll look like.

I'm curious as to why it seems adding Vizy B within Vizy A is OK, while Vizy A within Vizy A is not.

**Comment by JshGrn** [comment]
@tremby How did you end up resolving this?

**Comment by tremby** [comment]
I'm afraid I don't have anything useful to say. We decided in the end that Vizy was too unstable and backtracked to Neo for this project. We'll give it another look next time.

**Comment by engram-design** [comment]
> I'm curious as to why it seems adding Vizy B within Vizy A is OK, while Vizy A within Vizy A is not.

@tremby Mostly because adding the same instance of a field to itself isn't really possible with Craft. There's talk of Craft adding a new concept of "field instances" which would greatly help our handling of fields, but that's a little while away. Sorry for not replying sooner!

**Comment by engram-design** [comment]
Closing to track in https://github.com/verbb/vizy/issues/45
