### ISSUE TITLE
Image picker is non-functional

### ISSUE THREAD

**Issue by tremby** [verbb/vizy#128]
**Description**

In the wysiwyg editor, if I click the image button to add an image I get a modal but it doesn't seem to do anything.

**Steps to reproduce**
1. Have an images volume
2. Have some images in that volume
3. Click the "image" icon in a Vizy wysiwyg

I get a modal but

- its main area is blank white, no images
- the site picker reacts to a click but doesn't drop down
- the search box lets me type but nothing happens
- the preferences icon at the right of the search box reacts to a click but nothing happens
- the sort chooser reacts to a click but doesn't drop down

The cancel button does work, and closes the modal.

**Additional info**
- Plugin version: dev-craft-4 at 910a814
- Craft version: 4 beta at 2fee2c67
- Multi-site: Yes

**Additional context**
- Headless mode
- The images volume stores its files in an S3 bucket
- I'm using Imager X, configured to use Imgix.
- I noticed this problem *before* I had set up S3, Imager X, Imgix but decided to worry about it later.

**Comment by engram-design** [comment]
Should be fixed for the `craft-4` branch along with some performance improvements from `craft-3` when dealing with lots of blocktypes for a field.

There's a similar issue for adding links which I'm still investigating, as the schema has changed from Craft 3 to 4, and other similar plugins like Redactor also have this issue.

**Comment by tremby** [comment]
Seems to work fine after your changes. Thanks!
