### ISSUE TITLE
GQL response: provide access to the AssetInterface object under VizyNode_Image

### ISSUE THREAD

**Issue by tremby** [verbb/vizy#129]
**What are you trying to do?**

Render good HTML for images coming back from the wysiwyg field.

**What's your proposed solution?**

Right now after selecting all possible fields in the query for `VizyNode_Image` I only get data such as this:

```
            {
              "type": "image",
              "tagName": "img",
              "text": "",
              "rawNode": "{\"type\":\"image\",\"attrs\":{\"id\":98,\"src\":\"http://my-host/my-image.jpg\",\"alt\":\"Placeholder image 1\",\"title\":\"\",\"url\":null,\"target\":\"\",\"transform\":\"\"}}",
              "marks": "[]",
              "html": "<img src=\"http://my-host/my-image.jpg\" alt=\"Placeholder image 1\" title=\"\">",
              "attrs": "{\"id\":98,\"src\":\"http://my-host/my-image.jpg\",\"alt\":\"Placeholder image 1\",\"title\":\"\",\"url\":null,\"target\":\"\",\"transform\":\"\"}",
              "content": "[]"
            },
```

Whereas I want things like
- image width and height
- *original* image width and height, if the above is giving the transformed ones
- other fields I might have attached to this sort of asset in Craft, such as copyright info
- ability to get extra transformed versions, eg for different resolutions for a `srcset`

So what I'd really like is a link through to the associated `AssetInterface` object, where I could query for any of those things I need.

I think the `id` which I see there as `98` within `attrs` is in fact the asset ID, so I could in theory make another query after getting this response. But it would be much cleaner and faster to get everything I need in one query.

**Comment by tremby** [comment]
Or am I better off not allowing plain images, and instead using a Vizy Node with an asset field?

**Comment by engram-design** [comment]
Added support to query `asset` on a `VizyNode_Image` for the next release. This will allow you to query everything you'd normally do on an asset element. To get this early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-3 as 1.0.13",
  "...": "..."
}
```

Then run `composer update`.

**Comment by tremby** [comment]
Thank you. I can only use the Craft 4 version at present; I hope this'll make it into that before too long.

**Comment by engram-design** [comment]
Added in [2.0.0-beta.4](https://github.com/verbb/vizy/releases/tag/2.0.0-beta.4)
