### ISSUE TITLE
Entry selection doesn't work with Typed Link Field within a Vizy block on multisite.

### ISSUE THREAD

**Issue by wolf-em** [verbb/vizy#132]
**Description**

When using the sebastianlenz/linkfield plugin to render a link within the context of a Vizy field, selecting a related entry returns a null href attribute for the rendered link. This only seems to occur on multisite installations.

**Steps to reproduce**
1. Add at least two sites to a Craft install
2. Install Vizy and sebastianlenz/linkfield plugins
3. Create a Vizy field
4. Add a block that uses the link field.
5. Add the Vizy field to an entry type
6. Within the entry, add the link field and select another entry as the target url
7. Render the template and test the link.

**Additional info**
- Plugin version: Vizy 1.0.13, Typed link field 1.0.25
- Craft version: 3.7.38
- Multi-site: Yes

**Additional context**

**Comment by engram-design** [comment]
I must be missing something, because I don't see any issue on my end with this?

<img width="674" alt="image" src="https://user-images.githubusercontent.com/1221575/165942185-602804db-b669-473e-803a-42019453f1d1.png">

```
{% for node in entry.vizyLink.all() %}
    {% if node.type == 'vizyBlock' %}
        {{ node.linkField.getLink() }}
    {% endif %}
{% endfor %}
```

Results in:
```
<a href="http://vizy.test/blog/test" target="_blank">Custom link text</a>
```

**Comment by wolf-em** [comment]
When the template uses the renderHtml() method to render the Vizy field containing a link block, the href attribute is empty. Only happens on multisite with entries added to at least two sites.
```
<div>
	{{ entry.pageContent.renderHtml() }}
</div>
```
`<a href="{{ button }}" aria-label="{{ button.ariaLabel }}" target="{{ button.target }}">{{ button.customText }}</a>`

**Comment by engram-design** [comment]
Hmm, I still can't replicate that. I don't suppose `button.url` makes a difference (it shouldn't)? Are the link field or Vizy field translatable? Is the entry you're linking to a different site to the one you're on? Is the entry with the Vizy field on the non-primary site?

What does a `{{ dump(button) }}` produce?

**Comment by engram-design** [comment]
Clsoing due to age
