### ISSUE TITLE
Drop the editor, keep the blocks

### ISSUE THREAD

**Issue by JeanLucEsser** [verbb/vizy#133]
**What are you trying to do?**
The ultimate matrix replacement.

**What's your proposed solution?**
An option to disable the wysiwyg (editor) part of Vizy.
Keep only Groups and Blocks.

In a nutshell, allow Vizy to be nothing more than a + sign ;)

**Comment by engram-design** [comment]
You _almost_ can at the moment, the only issue being that you can type paragraph text in the editor. Also mentioned https://github.com/verbb/vizy/issues/16

**Comment by JeanLucEsser** [comment]
Oops, sorry about the duplicate.
Yes, the idea is to not be in the editor, so disabling the ability to type anything except creating blocks.
