### ISSUE TITLE
[Craft 4]: Fields properties in block do not get saved

### ISSUE THREAD

**Issue by JeanLucEsser** [verbb/vizy#135]
**Description**

Changes to fields (required, name, ...) in blocks do not get saved.
Re-ordering them do get saved.

What's weird is that I was able to save changes to my fields the first time I added them to my first block.
But then, no more, removing and re adding a field does not change that.

**Steps to reproduce**

Hard to tell. I created a block, added two fields, changed their names and required properties, command saved, created a second block, added more fields, and from that moment, fields properties didn't get saved anymore.

**Additional info**
- Plugin version: latest
- Craft version: 4 RC1
- Multi-site: No

**Comment by engram-design** [comment]
Yep, the field layout designer from Craft has gotten a makeover for Craft 4. Some of the hooks we were using to listen to updates so we can save in the field (via Vue) are no longer there.

So, we've had to refactor that, and it's probably better in the long run, where we use `MutationObserver` to observe any UI changes made by the field layout designer (in jQuery) and update our field layout model in Vue, to be processed by Vizy.

To get this early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-4 as 2.0.0-beta.3",
  "...": "..."
}
```

Then run `composer update`.

**Comment by JeanLucEsser** [comment]
Works in dev-craft-4!
Thanx ;)
