### ISSUE TITLE
[Craft 4]: Saving entry generates a search index error

### ISSUE THREAD

**Issue by JeanLucEsser** [verbb/vizy#136]
**Description**

Saving an entry with a Vizy field (with some blocks) generates a queue search index error.

**Steps to reproduce**
1. Create a searchable Vizy field with a block with some searchable content (in my use case it's another Vizy field)
2. Put some content in and save the entry

**Additional info**
- Plugin version: latest
- Craft version: 4.0 RC1
- Multi-site: No

**Additional context**

Vizy fields without any blocks do not show this issue.

**Comment by engram-design** [comment]
I can't seem to replicate this, sorry - and I've tested with a bunch of different field setups. Can you share the error as shown in the queue job? And if that's not an overly helpful error, searching in your `storage/logs/queue.log` for `[queue.ERROR]` or the error message text for the queue job?

**Comment by JeanLucEsser** [comment]
Closing this for now as I can't seem to replicate it after upgrading to the latest build of craft-dev-4.
Sorry about this.

**Comment by JeanLucEsser** [comment]
Oops, reopening... that didn't take long ;)

Here's the log:

```log
2022-04-29 09:37:34 [queue.ERROR] [craft\queue\QueueLogBehavior::afterError]  [2073] t9n:["app","Updating search indexes"] (attempt: 1, pid: 54) - Error (time: 0.127s): craft\hel
pers\Template::raw(): Argument #1 ($value) must be of type string, null given, called in /app/vendor/verbb/vizy/src/base/Node.php on line 124 {"memory":29088176}
2022-04-29 09:37:34 [queue.ERROR] [TypeError] TypeError: craft\helpers\Template::raw(): Argument #1 ($value) must be of type string, null given, called in /app/vendor/verbb/vizy/
src/base/Node.php on line 124 and defined in /app/vendor/craftcms/cms/src/helpers/Template.php:150
```

Is that enough or do you need me to try and replicate and documenting the full field setup from scratch?

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-4 as 2.0.0-beta.3",
  "...": "..."
}
```

Then run `composer update`.

**Comment by JeanLucEsser** [comment]
Looks like it's fixed. Thanx!
