### ISSUE TITLE
FR: Ability to add custom buttons to toolbar

### ISSUE THREAD

**Issue by mattbloomfield** [verbb/vizy#137]
**What are you trying to do?**
A description of what you want to happen.

I would like to be able to add a special link button for email links (that prepends the `mailto:` but possibly other buttons down the road

**What's your proposed solution?**
A description of how you think this could be solved, including any alternatives that you considered.

Similar to redactor, allow us to add custom buttons with custom icons and then we can pick up the tag in our formatter. 

**Additional context**

**Comment by JeanLucEsser** [comment]
I touched on something similar in another issue (see #131).
Looks like they are working on this via a full API so we can create custom buttons and dropdown's:

> Agreed, and we're working on an API for custom buttons! This will likely need to be paired with a Vue component, but still working on the details for that, and how best to approach this. Ideally, I'd like to expose and allow developers to make use of what [Tiptap](https://tiptap.dev/guide/node-views#markup) does with regards to parsing the node structure and parsing the DOM nodes

Vizy looks very promising, we just need to be patient.

**Comment by mattbloomfield** [comment]
Oh nice, thanks for the link. I had looked for a similar issue but missed yours. 

Fwiw we took a chance on vizy and implemented it for a big redesign we launched in October and it's been nothing short of fantastic. In the 6 months of being a live site we've had only one issue that required a rollback and that was resolved within days.

**Comment by dlindberg** [comment]
Just clarifying, #150 was a prerequisite for this feature, but doesn't enable it yet? This looks like it would be a massive improvement for long form content, but need a couple extra buttons to make it work for the content folks.

**Comment by engram-design** [comment]
@dlindberg We've always used Tiptap v2 (which is still in beta), but yes adding extensibility options is high on my list. Bug reports and other stability issues do come first though, but still looking to implement them this year.

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0). Have a read through the [blog post](https://verbb.io/blog/vizy-2-1), the [extensibility docs](https://verbb.io/craft-plugins/vizy/docs/template-guides/extending-vizy) and the [user guides](https://verbb.io/craft-plugins/vizy/docs/user-guides)
