### ISSUE TITLE
[FR] Question - How to migrate from matrix layout to vizy?

### ISSUE THREAD

**Issue by tomkiss** [verbb/vizy#138]
**What are you trying to do?**
I'd like to move existing content held in matrix fields to a Vizy field, but unsure how to achieve this.

Websites I build in Craft traditionallu use matrix blocks to achieve maximum editing options, but Vizy offers a much better author experience. I'd essentially like to port matrix fields over to a Vizy layout. I've never done anything like this before so am not sure where to start. Perhaps an import/export process using [FeedMe](https://docs.craftcms.com/feed-me/v4/)? Is there any additional functionality within Vizy that might help to do this?

**What's your proposed solution?**
I don't have one, but am curious if anyone else has done this or can offer advice in some way. I couldn't see any related issues on github so wanted to ask the question, incase discussion over time is helpful to others.

**Comment by engram-design** [comment]
At the moment, there aren't any plans to include migrations to/from Matrix/Neo/Super Table/others, sorry. If there's enough interest, we can maybe implement something, but it'll be difficult, as they're not 1-for-1 compatible.

**Comment by tomkiss** [comment]
Thanks for your response.
This is entirely understandable, but I do think having _any_ sort of import/export ability could be critically helpful for Vizy. 
If the node structure itself could be exported and re-imported, as a working process, then it would be a great starting point for users to build on top of, with more specific requirements. Though I appreciate it's no small feat!

**Comment by engram-design** [comment]
We're probably going to introduce an import/export of sorts via https://github.com/verbb/vizy/issues/142 where you can import and export raw HTML. This will at least help getting to/from other editors like Redactor, CKEditor, etc.

Where it gets really tricky is trying to migrate Vizy Block data, which is far down the todo list. But I agree, we want people to be able to come and go with Vizy as a WYSIWYG editor at the very least.
