### ISSUE TITLE
Collapsed Custom Vizy Blocks with Preview Text Don't Update When Adjusting Placement

### ISSUE THREAD

**Issue by zhua89cc** [verbb/vizy#139]
**Description**
We have a vizy field with a bunch of different custom vizy blocks. Because we have so many on a page sometimes the editors like to collapse them to move them around. When collapsed it looks like the block will append the first field value next to the block type . However it looks like the preview text doesn't get updated when the block is dragged to a different spot.

**Steps to reproduce**
1. Create an entry that has a vizy field in it's layout. Add two custom blocks to the vizy field. Make sure the custom vizy blocks have fields in them.
2. Add the two different types of custom vizy blocks onto the entry. Collapse the blocks and see that they take the value of the first field appended after the block name
3. Drag and move one of them to a different place and notice that now the block name has moved with it but it is now taking the preview text of the block that used to be there.

Loom Link
[https://www.loom.com/share/004a05f890d34dcbabeb5e6fd111528c](url)

https://user-images.githubusercontent.com/50242161/166265150-459a5ab1-cdb9-4c3d-bd84-cb9ef300aa87.mp4

**Additional info**
- Plugin version: 1.0.13
- Craft version: 3.7.28
- Multi-site: No

**Additional context**

**Comment by mattbloomfield** [comment]
+1

**Comment by engram-design** [comment]
Fixed in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0)
