### ISSUE TITLE
[FR]: Add description to vizy blocks

### ISSUE THREAD

**Issue by leevigraham** [verbb/vizy#143]
**What are you trying to do?**
A description of what you want to happen.

Webflow has a help menu that pops out when you hover over a block. This is helpful self documenting feature I think Visy could benefit from.

![image](https://user-images.githubusercontent.com/25124/169178630-78188cff-27e2-4aca-a5e3-7b2ad76a5125.png)

**What's your proposed solution?**

Add a new `description` field to the block editor that supports markdown. Not sure how a dev would add the video preview, I guess adding video markup in the markdown field? A gif could just be an image.

**Comment by engram-design** [comment]
Closing in favour of https://github.com/verbb/vizy/issues/60
