### ISSUE TITLE
Package ueberdosis/html-to-prosemirror is abandoned

### ISSUE THREAD

**Issue by richhayler** [verbb/vizy#144]
I noticed that one of the packages that Vizzy relies on appears to have been abandoned. Are you planning to switch out Vizzy's dependency on this to something else in the future?

**Comment by engram-design** [comment]
At some point, but the [successor package](https://github.com/ueberdosis/tiptap-php) is a little bit different, and we might even roll our own, still mulling over how to handle it, as we also want to write better handling of HTML-to-Vizy support.

**Comment by engram-design** [comment]
Updated in [2.0.7](https://github.com/verbb/vizy/blob/craft-4/CHANGELOG.md#207---2022-09-25)
