### ISSUE TITLE
JS errors when using a Vizy Field in a Vizy block

### ISSUE THREAD

**Issue by JeanLucEsser** [verbb/vizy#149]
**Description**
I have a block with a simple Vizy field in it.
As soon as I try to add the block or interact in any way with it, it throws a bunch of errors in the console (see capture).

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/14908712/171637778-ff89936b-99a9-4a7e-bea0-4dfdbe23c36f.png">

Here is a capture of the field within a block.

<img width="784" alt="image" src="https://user-images.githubusercontent.com/14908712/171638104-49cba67f-4bdf-4861-8e05-6fbf71eab974.png">

**Additional info**
- Plugin version: 2.0.1
- Craft version: 4.0.3

**Comment by engram-design** [comment]
Should be fixed in [2.0.2](https://github.com/verbb/vizy/releases/tag/2.0.2)
