### ISSUE TITLE
Template paths not saving

### ISSUE THREAD

**Issue by johnj24** [verbb/vizy#157]
**Description**
Whenever I enter a template path into the block settings and hit save, the template path does not save and is blank when I come back to the field settings.

**Steps to reproduce**
1. Add template path to block settings
2. Hit Save
3. Come back to the block settings and the template path is blank

**Additional info**
- Plugin version: 2.0.2
- Craft version: 4.0.4
- Multi-site: No

**Comment by engram-design** [comment]
Fixed for the next release. To get the fix early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-4 as 2.0.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by johnj24** [comment]
The update works. Thanks, Josh!
