### ISSUE TITLE
Add Keyboard Shortcut for "Insert Link"

### ISSUE THREAD

**Issue by Kashkin** [verbb/vizy#162]
### What are you trying to do?

I rely on keyboard shortcuts, and really appreciate when standardised keyboard shortcuts are implemented.

Across most text editors (Google Docs, Redactor, CKEditor, GitHub) a keyboard shortcut is available for inserting a link.

It is commonly:
CTRL + k
OR
⌘ + k

### What's your proposed solution?

When a user presses the keyboard shortcut, the Insert Link dialog is opened. If possible, it would be ideal to have separate shortcuts for "Link to an entry", "Link to an asset", and "Link to a category".

CKEditor uses a chained keyboard command of CTRL + L, CTRL + K. This could be implemented for links:
Entry: CTRL + L, CTRL + E
Asset: CTRL + L, CTRL + A
Category: CTRL + L, CTRL + C

It would be great to have a simple shortcut for external links, and more complex shortcuts for internal links, which would likely only be used by power users.

### Additional context

[tiptap keyboard shortcuts](https://tiptap.dev/api/keyboard-shortcuts)

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0)
