### ISSUE TITLE
Add setting to make the Add Block button always visible

### ISSUE THREAD

**Issue by engram-design** [verbb/vizy#163]
### What are you trying to do?

Currently, only a new, empty line will show the "+" button to add a new block. Some users are confused by this, and having it always visible would be better.

### What's your proposed solution?

We also might implement a shortcut or command util for power users to type "/" to bring up a command palette.

**Comment by BenPicard** [comment]
I want that! This is a real issue for my clients.

**Comment by engram-design** [comment]
Added a "Block type picker behaviour" setting in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0). It would be impossible to always show the picker button, because we would need to know _where_ to place new blocks - so where does the add new block button sit?

So now, you can set it to be shown on hover (and click), which I think will help out a lot of people.
