### ISSUE TITLE
Opening an edit entry slideout within a vizy field removes the related entry

### ISSUE THREAD

**Issue by Mosnar** [verbb/vizy#166]
### Describe the bug

When editing an entry via slideout from an entries field within a slideout, the entry is removed from the relation field. The UI will not appear to update, but if you refresh the page, the entry will no longer be associated.

### Steps to reproduce

1. Add an "Entries" field to a Vizy field
2. While editing an entry, double-click a related entry within the vizy field to open a slideout. Close the slideout (with or without making changes)
3. Notice in live preview that the UI depending on that relationship disappears.
4. Refresh the page and see entry is no longer present in relation field.

### Craft CMS version

Craft Pro 4.2.0.2

### Plugin version

2.0.4

### Multi-site?

No

### Additional context

Other installed plugins:

Plugin | Version
-- | --
Amazon S3 | 2.0.1
Blitz Recommendations | 2.1.1
Cloner | 2.0.0
CP Field Inspect | 1.4.4
Elements Panel | 2.0.0
Embedded Assets | 3.0.4
Feed Me | 5.0.4
Field Manager | 3.0.1
Formie | 2.0.4
Imager X | 4.1.2
MatrixMate | 2.0.2
Navigation | 2.0.3
Palette | 2.0.0
Redactor | 3.0.2
SEOmatic | 4.0.7
Sprig | 2.1.0
Super Table | 3.0.0
Template Comments | 4.0.0
Typed link field | 2.1.3-rc
Typogrify | 4.0.0
Vite | 4.0.2
Vizy | 2.0.4

**Comment by engram-design** [comment]
So just to clarify, you're got an Entry > Vizy field > Vizy block > Entries field - all opened through the element slide-out?

Is this also when using Live Preview? I can't seem to immediately replicate that in a number of different ways I've tried.

**Comment by engram-design** [comment]
Unable to replicate, but let me know if it's still an issue.
