### ISSUE TITLE
Nested Vizy fields are removed after updating from `2.0.4` to `2.0.5`.

### ISSUE THREAD

**Issue by kennyheard** [verbb/vizy#170]
### Describe the bug

I have a Vizy field that contains nested Vizy fields. Choosing blocks within this nested field is no longer possible after updating from `2.0.4` to `2.0.5`. When editing an entry, the parent block appears, but the nested editor area for the nested field does not seem to render.

### Editing an entry on Vizy `2.0.4`:
![vizy-2 0 4](https://user-images.githubusercontent.com/48108330/183655752-eeaacafc-1662-4f1d-b177-439399926974.png)

### Editing an entry on Vizy `2.0.5`:
![vizy-2 0 5](https://user-images.githubusercontent.com/48108330/183655771-6b18d4f0-225d-44d1-9c98-2bc6866a33ea.png)

### Steps to reproduce

1. Create a Vizy field called `parent`.
2. Create a Vizy field called `child`.
3. Create a block within `parent` and add the `child` field to it.
4. Add `parent` to any entry type.
5. Create a new entry.
6. Attempt to add content to the `child` field.

### Craft CMS version

4.2.0.2

### Plugin version

2.0.5

### Multi-site?

No

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this fix early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-4 as 2.0.5",
  "...": "..."
}
```

Then run `composer update`.

**Comment by kennyheard** [comment]
Perfect, that solved the issue until the next release. Cheers!
