### ISSUE TITLE
Nested Vizy Block Toolbar Doesn't Stay Fixed

### ISSUE THREAD

**Issue by strandofgenius** [verbb/vizy#184]
### Describe the bug

When nesting a Vizy block that has the `toolbarFixed` set to `true` and act as a rich text editor within another Vizy block the nested toolbar does not stay fixed to the top. Only the parent Vizy block toolbar stays fixed.

### Steps to reproduce

1. Create a custom Vizy `.json` config that has the `toolbarFixed` option set to `true`
2. Create a Vizy field that will act as a nested rich text with the custom config selected and no block types or additional fields
3. Create a Vizy field and create a block that contains the nested rich text field
4. Assign the field to an entry type and put some long-form content into the nested rich text Vizy block and then scroll down.
5. You should see that the nested toolbar does not stay fixed to the top

### Craft CMS version

4.3.0

### Plugin version

2.0.8

### Multi-site?

no

**Comment by engram-design** [comment]
Yeah, this is something I need to figure out. In practice, it looks super weird when say the outer Vizy field's toolbar is fixed, and a nested Vizy field also is - you get multiple stacked toolbars which not only looks weird, but is pretty problematic to actually implement.

**Comment by engram-design** [comment]
Fixed in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0)
