### ISSUE TITLE
Paste as plain text

### ISSUE THREAD

**Issue by anvart** [verbb/vizy#186]
### Question

In Redactor there's a lovely `pastePlainText: true` option. I could not find anything similar in Vizy. Is there any chance Vizy has (will have) this feature?

**Comment by engram-design** [comment]
Should be more achievable when we handle https://github.com/verbb/vizy/issues/183 but there's also fortunately some ProseMirror events we can use to make this happen.

- `transformPastedText` for pasted plain text
- `transformPastedHTML` for pasted HTML
- `transformPasted` after converting text/HTML to JSON

**Comment by anvart** [comment]
@engram-design thank you for the answer. Looking forward to the feature! It's the only missing one that stops me from using the plugin.

I'm not sure if the issue should be closed or left open

**Comment by engram-design** [comment]
Yep, we'll keep this open to track progress.

**Comment by engram-design** [comment]
One thing worth asking, is actually how you see this behaviour to work? The `pastePlainText` for Redactor isn't something I've used before. Is that a config setting that enforces _everything_ pasted in the field to be plain text?

I should note that you can paste plain text with the `Ctrl/Cmd` + `Shift` + `V` keyboard shortcut right now. That's a pretty common shortcut for most software out there.

**Comment by anvart** [comment]
@engram-design well, yes, OS-wide shortcut is well known, but not for everyone. Clients make mess sometimes.

Thanks for handling the issue.

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0)
