### ISSUE TITLE
Admin view goes funky when <ul> or <ol> is followed by <h1>

### ISSUE THREAD

**Issue by MattAppleton** [verbb/vizy#191]
### Describe the bug

I think this must be a bug...?

When I enter text and format to a list, then immediately place an 'h1' heading after it, Vizy shows the text closed up with no space between the list and the heading. See pic below.

<img width="219" alt="Zircon-Screenshot 2022-12-22 at 18 10 38" src="https://user-images.githubusercontent.com/6295710/209199526-2bec1a66-c033-44a7-9d5a-78d8d9a1ca8e.png">

As you can see, regular paragraph + h2 styling looks  / behaves as expected, there's a gap above them in the editor.

On the front end everything is fine, things behave as we'd expect via css styling. See below  (apart from the issue that list items have 'p' tags inside them, but that isn't the problem in this instance...)

<img width="210" alt="Zircon-Screenshot 2022-12-22 at 18 24 02" src="https://user-images.githubusercontent.com/6295710/209202060-74862a06-d49e-440e-85c5-c085eff98280.png">

<img width="688" alt="Zircon-Screenshot 2022-12-22 at 18 23 27" src="https://user-images.githubusercontent.com/6295710/209202083-04fc0d46-2456-49f9-a0b3-31bdcfd24077.png">

—

But in the back end it looks very wrong — there should be a gap between the ul and the h1 elements so our users don't get confused!

thanks for looking!

### Steps to reproduce

1. make an ordered / unordered list in a Vizy field
2. then follow that with text formatted as 'h1'

### Craft CMS version

4.3.5

### Plugin version

Vizy 2.0.9

### Multi-site?

yes

### Additional context

this is happening in a staging environment, local and remote...

**Comment by engram-design** [comment]
Yep, this would be an unfortunate byproduct of Craft's own heading styles (or lack thereof) being applied in the control panel.

Should be fixed for the next release. To get this fix early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-4 as 2.0.9",
  "...": "..."
}
```

Then run `composer update`.

**Comment by MattAppleton** [comment]
Many thanks Josh — that works a treat :)

Big improvement.

**Comment by MattAppleton** [comment]
@engram-design  — I don't suppose the[ text-field-height issue](https://github.com/verbb/vizy/issues/175#issue-1376514183) is targeted for in future releases?
