### ISSUE TITLE
Vizy broken when nested with Neo

### ISSUE THREAD

**Issue by LiamDotPro** [verbb/vizy#192]
### Describe the bug

When trying to use this plugin with neo I get the following error:

    Uncaught TypeError: bd.defineSimpleMode is not a function
        at codemirror-editor-vue3.es.js:239:14
        at vizy.cb2fc52f.js:1:637
        at vizy.js:69:2

and the editor is hidden as follows:

![image](https://user-images.githubusercontent.com/13067327/211404178-224f6b3f-1077-481b-b63d-575d0da46386.png)

### Steps to reproduce

1. Install new Craft
2. Install Neo
3. Install Vizy
4. try and add a vizy editor inside a neo block

### Craft CMS version

Craft Pro 4.3.6

### Plugin version

2.0.10

**Comment by engram-design** [comment]
Can't seem to replicate this immediately, sorry. Seems to be related to the CodeMirror component we use to edit HTML.

What settings does your Vizy field have - in particular the enabled WYSIWYG buttons?

**Comment by LiamDotPro** [comment]
hey @engram-design I've tried having a load of differnt options, 

current config

      {
          "buttons": ["html", "formatting", "h1", "h2", "h3", "h4", "h5", "h6", "bold", "italic", "underline", "strikethrough", "subscript", "superscript", "ordered-list", "unordered-list", "code-block", "hr", "highlight", "align-left", "align-right", "align-center", "align-justify", "clear-format", "line-break", "link", "image", "undo", "redo"],
          "formatting": ["paragraph", "code-block", "blockquote", "h1", "h2", "h3", "h4", "h5", "h6"],
          "toolbarFixed": true
      }

Althought we've tried it with the base config and also this

      {
          "buttons": ["bold", "italic", "underline", "strikethrough", "subscript", "superscript", "link", "image", "undo", "redo"],
      }

That and of course the default which is where we are at atm

**Comment by LiamDotPro** [comment]
@engram-design This can be closed, the issue was because we also had the codemirror plugin installed.

**Comment by engram-design** [comment]
Ah yes, related to https://github.com/verbb/vizy/issues/182 - I should've checked that.
