### ISSUE TITLE
How does Vizy handle field handle changes?

### ISSUE THREAD

**Issue by mattbloomfield** [verbb/vizy#193]
### Question

So I have a field in use on my site with the handle of videoid. I changed it to videoId, and Project Config took care of the migrations it seems because anywhere I was using it still had the right data. 

However, I have a few vizy blocks that use that field, and those blocks just lost their data (this is all local, so no actual data loss). 

My question is, (and I fully realize this could lead to a bug report), should I expect Vizy to pick up on the handle change? Because of the way it stores everything in a JSON blob I can't figure out how it would handle that - but maybe I'm missing something?

**Comment by engram-design** [comment]
You're correct, we would need to listen to every field change, go through every Vizy field's content, scour it's contents for the occurrence of that field, and rename the field handle. Currently, Vizy doesn't support that, but it's probably a necessity for sure, and just one of the drawbacks of storing field content as JSON.

**Comment by BenParizek** [comment]
@engram-design We've just run into this again and it really feels like a bug when it happens as you have to be constantly aware that Vizy is behaving differently around field handles than the rest of the field uses in the CMS.

**Comment by engram-design** [comment]
@BenParizek yep, will be addressed in 2.1.0 which isn’t far away

**Comment by engram-design** [comment]
Updated in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0). Now, each time a field that's been included in a Vizy field changes, the change to the content for the Vizy field is made.
