### ISSUE TITLE
Upgrading to 2.0.11 breaks GraphQL

### ISSUE THREAD

**Issue by tom-bywild** [verbb/vizy#196]
### Describe the bug

After updating `verbb/vizy` to version `2.0.11` from previous `2.0.10`, I encountered a broken GraphQL integration. The issues:

- no schema could be loaded
- query didn't work that previously was stable
- type generation didn't work any more in the FE (not part of this package)

After reverting to `2.0.10` (which also was a pain, as `2.0.11` introduces the `initialRows` field, which breaks a downgrade and effectively required me to delete all vizy-fields first), the GraphQL explorer can be loaded again.

| Image | Description |
| --- | --- |
| <img width="1759" alt="screenshot_2023-02-23_at_20 27 44" src="https://user-images.githubusercontent.com/102795185/221013016-74cee24c-7743-4ea7-a3e5-d9178604070d.png"> | Screenshot of GraphiQL w/ broken explorer and broken query that worked before |
| <img width="881" alt="Screenshot 2023-02-23 at 20 31 45" src="https://user-images.githubusercontent.com/102795185/221013783-b7150865-693c-4664-bd32-420fbb8890dc.png"> | Error after downgrading for the first time |

### Steps to reproduce

1. Update to version `2.0.11`
2. See issue

### Craft CMS version

Craft Pro 4.3.10

### Plugin version

2.0.11

### Multi-site?

No

**Comment by engram-design** [comment]
Are you able to give the latest `craft-4` changes a go? There were some issues fixed with GraphQL. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.0.11"`

**Comment by tom-bywild** [comment]
Hi @engram-design 👋 thanks for the quick response, this version fixes all issues 🤙

**Comment by tom-bywild** [comment]
As another thought, do you think it would make sense to add an automated integration test to this repo? I would imagine a Github Action using a [Craft Docker Image](https://github.com/craftcms/docker). We run a migration or data dump first, then query for the entities. I think this could catch such an issue early.

I'd be open to contriute.

**Comment by engram-design** [comment]
That's certainly a possibility, although I worry about the maintainability of such a thing (the database dump specifically). But yeah, anything to help with automated testing is something worth considering.

**Comment by engram-design** [comment]
Fixed in [2.0.12](https://github.com/verbb/vizy/releases/tag/2.0.12)
