### ISSUE TITLE
Unable to change heading to paragraph 

### ISSUE THREAD

**Issue by d-karstens** [verbb/vizy#197]
### Describe the bug

Hi,

We've noticed an issue where we're unable to change heading formatted text to a paragraph using the formatting menu, I've recorded a short video to demonstrate 

https://user-images.githubusercontent.com/21274925/221055902-13fb017d-0b77-4a39-832c-2eeb3f54a9cc.mov

One thing to note is that if we select the same heading option again it does change back to a paragraph

Let me know if you need any more info,
Thanks!

### Steps to reproduce

1. Use formatting menu to make a heading 
2. Try and change the heading to a paragraph

### Craft CMS version

4.3.10

### Plugin version

2.0.11

### Multi-site?

No

**Comment by engram-design** [comment]
I believe this might be an upstream Tiptap issue, but looking into it!

**Comment by engram-design** [comment]
Fixed in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0)
