### ISSUE TITLE
Migrate Plain Text or Rich Text To Vizy

### ISSUE THREAD

**Issue by theskyfloor** [verbb/vizy#20]
**What are you trying to do?**

I would like to be able to select a Redactor, CKEditor, or plain text field and convert it to Vizy with no data loss.

**Additional context**

Vizy is so much better than existing editors, I want to use it for everything!

**Comment by clebuchegger** [comment]
anybody found a good solution to migrate a ckeditor field to a vizy field?

**Comment by engram-design** [comment]
This should be achievable with Feed Me which Vizy supports migrating just WYSIWYG content. So long as the HTML elements you're including are supported in Vizy.
