### ISSUE TITLE
Vizy 2.1.0 Table import using Feedme

### ISSUE THREAD

**Issue by davorpeic** [verbb/vizy#203]
### Question

Hi,
now that 2.1.0 supports inserting Table, would be possible to import also tables with Feedme in Vizy field?

thanks

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.0"`

**Comment by engram-design** [comment]
Added in [2.1.1](https://github.com/verbb/vizy/releases/tag/2.1.1)
