### ISSUE TITLE
Certain Command pallet options not working

### ISSUE THREAD

**Issue by jan-dh** [verbb/vizy#207]
### Describe the bug

Both the `Media embed` and the `Image` option from the Command Pallet don't seem to do anything

<img width="598" alt="image" src="https://user-images.githubusercontent.com/5801781/232785145-f8df1f4e-694c-41e8-85b3-bea0085ff442.png">

Clicking them, I don't see console logs, only nothing happening.

### Steps to reproduce

1. Create a vizy field
2. Try to add a media embed or image option

### Craft CMS version

4.4.7.1

### Plugin version

2.1.0

### Multi-site?

"yes"

**Comment by engram-design** [comment]
Quick question - do you have those buttons enabled in your buttons config? I have a feeling that's the issue, that they're included at the command palette level, when the button isn't (see comment https://github.com/verbb/vizy/issues/206)

**Comment by engram-design** [comment]
Fixed in [2.1.1](https://github.com/verbb/vizy/releases/tag/2.1.1)
