### ISSUE TITLE
Command Pallet - block types not editable

### ISSUE THREAD

**Issue by jan-dh** [verbb/vizy#208]
### Describe the bug

I think it's a bit weird that the node types mentioned in the Command pallet aren't being shown anywhere in the block configuration. Would be really helpful to show them there as default or something so they are extendable as well. 

### Steps to reproduce

1. Create a new vizy field
2. Check the block configuration, nothing's there.

### Craft CMS version

4.4.7.1

### Plugin version

2.1.0

### Multi-site?

"Yes"

**Comment by engram-design** [comment]
Mentioned in https://github.com/verbb/vizy/issues/206, agree this should be (easily) configurable, although you can control this with a Vizy Plugin.

**Comment by engram-design** [comment]
Added in [2.1.1](https://github.com/verbb/vizy/releases/tag/2.1.1). You can now provide a `commands` option in [editor config](https://verbb.io/craft-plugins/vizy/docs/get-started/configuration#commands) to manage options.
