### ISSUE TITLE
Editing vizy text in matrix field wil not save.

### ISSUE THREAD

**Issue by FransvdWijst** [verbb/vizy#216]
### Describe the bug

When using the vizy texteditor in matrix fields, the modifications will not be saved.
It won't update the preview page (update the draft) when editing content in the vizy teksteditor.

We noticed the problem in Vizy version 2.1.1 and updated vizy 2.1.3. So the problem was already active in V2.1.1.

We also have Craft 3 websites using the same setup, here the problem doesn't exist.

### Steps to reproduce

1. Create a Matrix blocktype and a field with Fieldtype: Vizy
2. Create a new vizy field, and add a vizy block containing the above matrix field.
![image](https://user-images.githubusercontent.com/105865888/234576214-d38a7d1f-0bc1-45bd-9569-90ab03f8c774.png)
3. Create a new entry (where this matrix block is used) ad some dummy tekst and save the entry (the content will be saved correctly)
4. Open the saved entry, and try to edit the vizy content in the matrix field. You will notice the field doesn't update the draft, the preview is not updated and the modifications won't be saved.

This is how my test page looks like:
![image](https://user-images.githubusercontent.com/105865888/234576625-d82e6edc-c30d-4887-81c3-2cb7d20dafe6.png)

### Craft CMS version

Craft Pro 4.4.7.1

### Plugin version

2.1.3

### Multi-site?

Yes

**Comment by engram-design** [comment]
Just so I'm clear, refer to the screen recording for my steps to reproduce. Is that correct?

https://user-images.githubusercontent.com/1221575/234422352-77167138-940f-4b69-bb96-330ca0bbb668.mp4

**Comment by FransvdWijst** [comment]
I notice it is more specific then that.
There is a step in between which i missed. 

The basic setup is:
Vizy field -> Vizy Block container matrix field -> This matrix field containens another vizy field.

I updated the Steps to reproduce, and added screenshots to clarify. 
Later today I will be able to make a screen recording so you can see it happening.

**Comment by FransvdWijst** [comment]
As promised, a screen recording:[](url)

https://user-images.githubusercontent.com/105865888/234643488-1516c344-7a88-4099-9d5b-3883236e4967.mp4

**Comment by engram-design** [comment]
Ah, that makes sense. Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.3"`

**Comment by FransvdWijst** [comment]
Today we ware able to test the fix via version "dev-craft-4".

This did fix tix the isseu when editing the tekst within a matrix field.
With this fix, another error appears. 
If you want to add a new matrix element, the input field is not visible at all.
When you save the page, and re-open it for editing the input field will be visible,and then you will be able to add content.

At the moment I am not able to make screen recordings, but i am able to post screenshots:
![image](https://user-images.githubusercontent.com/105865888/235459424-feda60cc-b9bb-42bf-b133-660de60d5815.png)
![image](https://user-images.githubusercontent.com/105865888/235459488-fefe4593-eac0-4882-82dc-c249fa4d3af5.png)

Then save the page, and re-open. The field is shown and fully functional.
![image](https://user-images.githubusercontent.com/105865888/235459594-d3b35e09-86ac-4548-93a7-535df51eef46.png)

If a screencapture helps to clearify, just let me know. I will make sure i have one.

**Comment by engram-design** [comment]
Are you able to run `composer require verbb/vizy:"dev-craft-4 as 2.1.3"` again to see if (another) fix fixes that for you?

**Comment by engram-design** [comment]
Should be fixed in [2.1.4](https://github.com/verbb/vizy/releases/tag/2.1.4)
