### ISSUE TITLE
Will Vizy be switching to CKE as editor?

### ISSUE THREAD

**Issue by jan-dh** [verbb/vizy#217]
### Question

With the switch from Redactor to CKE a lot of added functionality, I wonder if it's an idea to switch from (I don't know which editor you are using behind the scenes) to CKE somewhere in the near future?

**Comment by engram-design** [comment]
We have no plans to switch to CKEditor, as Vizy uses [Tiptap](https://tiptap.dev) which itself uses [ProseMirror](https://prosemirror.net/). It's fundamentally a different approach, where content is saved as blocks, rather than the rendered HTML.
