### ISSUE TITLE
Iframe's don't generate src on front-end render

### ISSUE THREAD

**Issue by DowleyDeveloped** [verbb/vizy#219]
### Describe the bug

Within the CMS, if I add a Spotify Url into the iframe, I get a render popup.

`<iframe url="https://open.spotify.com/embed/playlist/37i9dQZF1EM5oL6QIRd0Sa?utm_source=generator" src="https://open.spotify.com/embed/playlist/37i9dQZF1EM5oL6QIRd0Sa?utm_source=generator" frameborder="0"></iframe>`

However on the front-end the html is renders as `<iframe url="https://open.spotify.com/embed/playlist/37i9dQZF1EM5oL6QIRd0Sa?utm_source=generator" frameborder="0"></iframe>`

So without a src it does not load.

### Steps to reproduce

1.  Add Spotify Embed Url into Iframe
2. View on front-end

### Craft CMS version

4.4.7.1

### Plugin version

2.1.3

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.3"`

**Comment by engram-design** [comment]
Should be fixed in [2.1.4](https://github.com/verbb/vizy/releases/tag/2.1.4)
