### ISSUE TITLE
Access owner within a block field

### ISSUE THREAD

**Issue by adrienpicard** [verbb/vizy#22]
**What are you trying to do?**
I'm setting up an Asset block and want to use the Entry slug as the default upload path. 

**What's your proposed solution?**
It would be great to use the `owner` keyword, as you would in a Matrix field.

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-3 as 1.0.1",
  "...": "..."
}
```

Then run `composer update`.

**Comment by adrienpicard** [comment]
Thanks @engram-design. Closing in favor of #27 as I'm having similar issues.
