### ISSUE TITLE
Vizy fields getting wiped

### ISSUE THREAD

**Issue by josh-attwood** [verbb/vizy#221]
### Describe the bug

We have had this issue quite a lot in the past but I think we have finally gotten to the bottom of the cause. We have a scenario where vizy fields get totally wiped (which previously seemed totally random). It seems to be something to do with the way Vizy interacts with Craft drafts and 'Entries' fields. We mainly see this happen on Vizy fields within Vizy fields, we have a simple Vizy field as a text editor which we often add to a larger Vizy block.

### Steps to reproduce

1. Find an entry which includes an 'entries' field and open it
2. Double click on the linked entry which opens the side panel for editing this related entry (this entry must have a vizy field)
3. Notice that Craft automatically creates a new draft here regardless of whether you edit any content
4. Click the button in the top right of this pull out window to open the sidebar entry in a full page
5. You should see that Vizy blocks have been wiped

### Craft CMS version

Craft Pro 4.4.3

### Plugin version

dev-craft-4

### Multi-site?

Yes

**Comment by engram-design** [comment]
Yeah, so the element editor slideout treats things differently to editing content "normally" which is a bit frustrating. I imagine you don't get this behaviour when editing entries directly?

Just a quick video to describe this as well https://share.cleanshot.com/kS4NrqM2

**Comment by engram-design** [comment]
Should be fixed in [2.1.4](https://github.com/verbb/vizy/releases/tag/2.1.4)
