### ISSUE TITLE
Upload a file button on asset field not woking

### ISSUE THREAD

**Issue by aodihis** [verbb/vizy#225]
### Describe the bug

I have an asset field on `vizy` field with allowed to upload file directly is active. But when I click the Upload a file there is nothing happens.

Also it only happen when the asset field is inside `vizy`, if the asset field is standalone it is fine.

And also it only happen recently after I update the plugin.

### Steps to reproduce

1.  Create a vizy field with asset field inside it.
2.  Set the allow upload field directly to true.
3. Click  on 'Upload a file' and nothing happen.

### Craft CMS version

4.4.9

### Plugin version

2.1.4

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.4"`

**Comment by engram-design** [comment]
Fixed in [2.1.5](https://github.com/verbb/vizy/releases/tag/2.1.5)
