### ISSUE TITLE
With nested Vizy fields, dropdowns default are not populated

### ISSUE THREAD

**Issue by bleepsandblops** [verbb/vizy#228]
### Describe the bug

If you nest 2 Vizy fields with a dropdown in the second one, that dropdown default value doesn't get populated automatically. It's particularly problematic if that field is hidden behind a tab as the entry refuses to save and you have to click all the tabs to find the error message.

Works fine without the nesting.

### Steps to reproduce

1. Create a Vizy field with just one dropdown field in it, and a default value.
2. Create another Vizy field and add the one from step 1. as a block
3. Attach that field to an entry, open the entry
4. The dropdown field's default is not populated.
5. If you do it without the nesting, it populates fine.

### Craft CMS version

4.4.11

### Plugin version

2.1.4

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.4"`

**Comment by engram-design** [comment]
Fixed in [2.1.6](https://github.com/verbb/vizy/releases/tag/2.1.6)
