### ISSUE TITLE
Field on matrix become too close if it is use 1 column

### ISSUE THREAD

**Issue by aodihis** [verbb/vizy#229]
### Describe the bug

In my vizy we have a block with matrix field inside it, and inside there are 2 dropdown with column is set to one each. And it become too close. 
This only happen on vizy if I put the field directly on entry it is looks fine.
<img width="572" alt="Screen Shot 2023-06-05 at 12 57 29" src="https://github.com/verbb/vizy/assets/18330728/a29ca42d-31be-4e7b-aad1-f9b582ed4b09">

### Steps to reproduce

1. Create a vizy block with matrix inside it and inisde matrix add a field with one column.

### Craft CMS version

4.4.13

### Plugin version

2.1.6

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.6"`

**Comment by engram-design** [comment]
Fixed in [2.1.7](https://github.com/verbb/vizy/releases/tag/2.1.7)
