### ISSUE TITLE
Nested Vizy field inside of Supertable not displaying

### ISSUE THREAD

**Issue by twitcher07** [verbb/vizy#234]
### Describe the bug

I have a matrix field called "Content Builder" and inside that I have a block type called "Heading & Content Split" that contains a vizy field that has an element called "Accordions" that's supertable with another vizy field.

Here is a screenshot of my matrix setup:
![Screenshot 2023-06-22 at 4 49 20 PM](https://github.com/verbb/vizy/assets/8517321/c19f6256-787d-47a2-b831-6367544ae4d0)

Notice the "Accordion" in the vizy field. That is the one that is a supertable that contains another vizy field.

When first adding this block the vizy field inside the accordion isn't visible.
![Screenshot 2023-06-22 at 4 43 42 PM](https://github.com/verbb/vizy/assets/8517321/6696340f-970c-4b12-99f7-1c820a8c0f96)

But if I save the entry and then come back to it, it seems to display just fine.
![Screenshot 2023-06-22 at 4 44 12 PM](https://github.com/verbb/vizy/assets/8517321/cd5c8ad1-1ce2-47e5-b756-f27e90fe0122)

I don't see any errors in the console. Any insight on what's going on?

### Steps to reproduce

1. Create a matrix field with a block type that contains a vizy field.
2. Create a supertable field that contains a vizy field.
3. Add the supertable field as a block inside of the vizy field inside the original matrix field from step `#1`

### Craft CMS version

4.4.13

### Plugin version

2.1.6

### Multi-site?

no

**Comment by JshGrn** [comment]
I am getting the same issue, this is holding up a project being given to the client for me. @engram-design sorry to tag you but have you looked at this at all?

**Comment by JshGrn** [comment]
@engram-design have you had any luck looking into this one? Still getting this and having to tell clients to save with errors which is far from ideal in order for the fields to correctly initialise

**Comment by JshGrn** [comment]
@twitcher07 did you ever resolve this? This is causing me a lot of delay now and considering having to swap it to Neo which I **really** do not want to do.

**Comment by engram-design** [comment]
So this is somewhat of a known issue, and I'm looking into our options here. The issue being that when new blocks are created (Matrix or Super Table), HTML is added using jQuery. It's adding the appropriate Vue code that Vizy needs `<vizy-input>`, but because it's being done with jQuery, Vue isn't getting bound correctly.

Refreshing the page should kick it into gear, but I'm well aware that's not a permanent fix.

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.7"`

**Comment by twitcher07** [comment]
@engram-design Awesome! I appreciate the work.

I will update the plugin and test.

**Comment by twitcher07** [comment]
@engram-design after updating the plugin it seems like it is fixed and vizy fields seem to be working properly for new matrix blocks. However existing matrix blocks that contained vizy fields now seem to be missing the vizy field. See the below screen shots for examples.

New matrix block that contained a vizy field with a supertable containing another vizy field that is working properly:
![image](https://github.com/verbb/vizy/assets/8517321/06a9144d-8bf7-421b-8ba9-8d1ab599d4f3)

Matrix blocks that had already existed which should contain vizy fields:
![image](https://github.com/verbb/vizy/assets/8517321/b2bae1b1-1d46-449b-86f6-82d2c652afe4)

In case it helps, I don't see any javascript errors in the console.

**Comment by engram-design** [comment]
Okay, I think I've gotten to the bottom of these initializing issues by revamping how Vizy is loaded. There's been way too many edge-cases and weirdness for my liking! There's lots to deal with from nested Vizy fields, to the element slideout (quick-editing an entry) to this with Matrix/ST/Neo.

Have a double check on this running `composer require verbb/vizy:"dev-craft-4 as 2.1.7"`

**Comment by engram-design** [comment]
Fixed in [2.1.8](https://github.com/verbb/vizy/releases/tag/2.1.8)

**Comment by twitcher07** [comment]
@engram-design yep, I can confirm it's fixed. Thank you so much for looking into this!
