### ISSUE TITLE
Set (Default) Asset Location Dynamically 

### ISSUE THREAD

**Issue by kerns** [verbb/vizy#24]
**What are you trying to do?**
I would like a method for dynamically specifying the default location for images inserted via the toolbar with Vizy on any given entry.

**What's your proposed solution?**
I don't know if this is the best way to do it, but this is *a* way. And one Craft heads are probably already familiar with 👇

<img width="528" alt="Screen Shot 2021-05-21 at 14 42 45" src="https://user-images.githubusercontent.com/20254/119139065-e5be6480-ba42-11eb-8eea-2e222e03481d.png">

**Comment by engram-design** [comment]
Yep, we'll add that as a setting on the field settings, much the same way Assets does (as above).

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0)
