### ISSUE TITLE
Embed media doesn't show after switching to HTML and back

### ISSUE THREAD

**Issue by davorpeic** [verbb/vizy#240]
### Describe the bug

Hi,

it looks like some issue with encoding/re-encoding iframe url, Once embed VT video is added, it shows up ok, swtich to HTML view and back to normal view, video is not loaded anymore, every new switch to HTML I see tags are encoded again, so I will assume they are not returned to original state when switched from HTML->normal

![image](https://github.com/verbb/vizy/assets/694091/d84657f6-b92c-4562-a0b8-6de09f11a4ab)

### Steps to reproduce

1. Add simple youtube video
2. switch to HTML view
3. switch back to normal view

### Craft CMS version

4.4.15

### Plugin version

2.1.7

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.7"`

**Comment by engram-design** [comment]
Fixed in [2.1.8](https://github.com/verbb/vizy/releases/tag/2.1.8)
