### ISSUE TITLE
Multiple instances of a vizy field break it

### ISSUE THREAD

**Issue by jan-dh** [verbb/vizy#241]
### Describe the bug

I have multiple super table fields, with a vizy field inside of those. 
I get a lot of JS messages in the console (not sure if related)
<img width="489" alt="image" src="https://github.com/verbb/vizy/assets/5801781/f4d4e3e8-e17b-4aeb-94e6-9d61f459f895">

and the vizy block stays empty. Inside the block is a single supertable field

### Steps to reproduce

So the setup:

Multiple super table field.
Each of these have a vizy field. 
Within that vizy field there is a super table.

### Craft CMS version

4.4.15

### Plugin version

2.1.7

### Multi-site?

yes

**Comment by jan-dh** [comment]
Additional console errors:

<img width="1390" alt="image" src="https://github.com/verbb/vizy/assets/5801781/7ba8a051-7405-41b4-9717-4521db89384c">

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.7"`

**Comment by engram-design** [comment]
Fixed in [2.1.8](https://github.com/verbb/vizy/releases/tag/2.1.8)
