### ISSUE TITLE
Nested Vizy field shows unsaved changes message unnecessarily 

### ISSUE THREAD

**Issue by rmales** [verbb/vizy#243]
### Describe the bug

Following from https://github.com/verbb/vizy/issues/242. When I have a nested Vizy field in an entry, after that entry is first saved just focusing the nested field (without editing it) always shows the "Showing your unsaved changes" message.

### Steps to reproduce

1. Create a Vizy field containing a block containing another Vizy field and add that to an entry type
2. Create an entry of that type, add the block, and save the entry
3. Edit the entry and focus the nested Vizy field

### Craft CMS version

4.4.16.1

### Plugin version

dev-craft-4 as 2.1.7

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.7"`

**Comment by engram-design** [comment]
Fixed in [2.1.8](https://github.com/verbb/vizy/releases/tag/2.1.8)
