### ISSUE TITLE
Trim Empty Nodes

### ISSUE THREAD

**Issue by kerns** [verbb/vizy#25]
Some sort of `trimEmptyNodesOnSave` pref would be very nice if possible, and not dangerous. Most editors won't notice this empty `p` tag ...not on the backend nor the frontend.
`>--- ☹️--------<`
<img width="640" alt="Screen Shot 2021-05-21 at 17 21 29" src="https://user-images.githubusercontent.com/20254/119161261-66885b00-ba59-11eb-8a84-908dfcdb19bf.png">

**Comment by engram-design** [comment]
Sure, certainly will mark this as an opt-in thing, as I've come across **many** clients who want to create a bit more space with line breaks. Right or wrong, it's a common enough thing to warrant both options here.

**Comment by kerns** [comment]
If they are indeed line breaks and not empty p tags that would make sense/feel better.

**Comment by engram-design** [comment]
They're considered the same thing with ProseMirror/Tiptap, so maybe that'll be an issue. Or a hard break can contain a `<br>` so it's considered non-empty.

**Comment by engram-design** [comment]
Added a new field setting to control this for the next release. To get this early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-3 as 1.0.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.0.3](https://github.com/verbb/vizy/releases/tag/1.0.3)
