### ISSUE TITLE
Add "title" field to links for accessibility

### ISSUE THREAD

**Issue by jakedohm** [verbb/vizy#253]
### What are you trying to do?

I'd like to be able to add a "custom title" field to this view, for accessibility reasons.
<img width="669" alt="CleanShot 2023-09-06 at 11 28 16@2x" src="https://github.com/verbb/vizy/assets/20726308/417e33a3-4852-4dd5-b860-dd6fd31caa4a">

### What's your proposed solution?

Adding an optional, and potentially configurable (enable/disable) field to the link options for a link title.

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.8"`

**Comment by engram-design** [comment]
Added in [2.1.9](https://github.com/verbb/vizy/releases/tag/2.1.9)

**Comment by jakedohm** [comment]
@engram-design thank you so much for the quick turnaround on this, it's uber-appreciated!!
