### ISSUE TITLE
UL inside table doesn't render in the CMS

### ISSUE THREAD

**Issue by jan-dh** [verbb/vizy#259]
### Describe the bug

When creating or copy/pasting a UL inside a table cell, it's not shown as a UL inside the cell in the CMS. Content does render well on the front end twig template.

### Steps to reproduce

1. Create a table
2. Copy/paste or create a UL inside a table cell

### Craft CMS version

4.5.5

### Plugin version

2.1.9

### Multi-site?

"Yes"

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.9"`

**Comment by engram-design** [comment]
Fixed in [2.1.10](https://github.com/verbb/vizy/releases/tag/2.1.10)
