### ISSUE TITLE
Hitting maximum character limit in Vizy field

### ISSUE THREAD

**Issue by JshGrn** [verbb/vizy#263]
### Describe the bug

When transferring exceptionally long content fields (Privacy Policy, Terms & Conditions) I have run into this on one of our sites:
![image](https://github.com/verbb/vizy/assets/75624794/ff8e7e15-573c-4d41-9a46-e93985785fda)

I have taken the html from the previous Redcactor field and pasted it in the HTML of the Vizy field, even saving as draft hits this limit. I am pretty sure you can recreate this using the Lipsum generator https://www.lipsum.com/ to create over that limit in characters.

### Steps to reproduce

1. Enter over 65k characters in Vizy field
2. Attempt to save

### Craft CMS version

Craft Pro 4.5.6.1

### Plugin version

2.1.11

### Multi-site?

No

**Comment by engram-design** [comment]
This means you've hit the limit of the storage type for the field. Have a look at the "Advanced" settings for a field to pick something larger.

<img width="396" alt="image" src="https://github.com/verbb/vizy/assets/1221575/eba40b46-9e8b-4f92-9371-4c629767b750">

**Comment by JshGrn** [comment]
Lol, how embarrassing...
