### ISSUE TITLE
Code block content disappearing after save

### ISSUE THREAD

**Issue by bpurtoncc** [verbb/vizy#266]
### Describe the bug

I have an issue where when I insert certain text into a code block it disappears after saving.

### Steps to reproduce

1. Add `<script src='https://127.0.0.1:8444/lib/telemlib.js'></script>` into a code block in Vizy.
2. Save the entry.
3. Code block will now be empty.

### Craft CMS version

Craft Pro 4.5.5

### Plugin version

2.1.10

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.12"`

**Comment by engram-design** [comment]
Fixed in [2.1.13](https://github.com/verbb/vizy/releases/tag/2.1.13)
