### ISSUE TITLE
Styled links in Vizy don't have an edit link tooltip when clicked

### ISSUE THREAD

**Issue by DrewTJohnson** [verbb/vizy#273]
### Describe the bug

When adding bold/italic/underling/etc to a link in the Vizy text field, the tooltip to edit the link no longer shows up.

https://github.com/verbb/vizy/assets/33323897/70039e93-7ca6-4641-9a73-aae91297727d

### Steps to reproduce

1. Add a link to the Vizy text box
2. Apply a style to said link
3. Attempt to click link to open up tooltip

### Craft CMS version

Craft Pro 4.5.11

### Plugin version

2.1.12

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.14"`

**Comment by engram-design** [comment]
Fixed in [2.1.15](https://github.com/verbb/vizy/releases/tag/2.1.15)
