### ISSUE TITLE
Text overflows out of field

### ISSUE THREAD

**Issue by d-karstens** [verbb/vizy#278]
### Describe the bug

Hi,
We've run into an issue where text overflows out of a Vizy field if a user doesn't start a new line

![Screenshot 2024-01-31 at 3 42 36 pm](https://github.com/verbb/vizy/assets/21274925/c10dfb80-efb5-44ed-bec2-b0f1569991d4)

We're on version. 2.1.15, but I tried rolling back to 2.1 to see if it was a recent issue we never noticed, and it still happened

### Steps to reproduce

1. Create a Vizy field
2. Type some text without starting a new line

### Craft CMS version

4.7.1

### Plugin version

2.1.15

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.15"`.

**Comment by engram-design** [comment]
Fixed in [2.1.16](https://github.com/verbb/vizy/releases/tag/2.1.16)
