### ISSUE TITLE
Dropdown in a Vizy block disappearing when nested in a super table field

### ISSUE THREAD

**Issue by bleepsandblops** [verbb/vizy#279]
### Describe the bug

I have a supertable field and within it a Vizy field type. I have several blocks within the Vizy field, and some of those blocks have dropdowns. 
If I move a block that has some dropdowns, the dropdowns disappear and i can see an error in the console:
<img width="571" alt="Screenshot 2024-01-31 at 15 19 36" src="https://github.com/verbb/vizy/assets/1942313/d886535a-0481-4508-bfcb-49104d66dfad">

Before / After of the dropdowns disappearing:
<img width="701" alt="Screenshot 2024-01-31 at 15 20 10" src="https://github.com/verbb/vizy/assets/1942313/1695a058-0a29-4679-8178-de3a32ae0f4b">
<img width="699" alt="Screenshot 2024-01-31 at 15 19 44" src="https://github.com/verbb/vizy/assets/1942313/7e1e36f9-aff1-4c18-8b31-eb05ee685789">
I can send a db dump or project config if it makes things easier to debug.

Side issue: the dropdowns need padding between them.

Thank you!

### Steps to reproduce

Cf above

### Craft CMS version

4.7.1

### Plugin version

2.1.15

### Multi-site?

No

**Comment by engram-design** [comment]
I believe this has to do with how we have to re-initialize Selectize, being jQuery and Vizy is in Vue there's some complexity there.

Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.15"`.

**Comment by engram-design** [comment]
Fixed in [2.1.16](https://github.com/verbb/vizy/releases/tag/2.1.16)
