### ISSUE TITLE
CKEditor field gets duplicated when moving the block

### ISSUE THREAD

**Issue by bleepsandblops** [verbb/vizy#284]
### Describe the bug

Looks very similar to https://github.com/verbb/vizy/issues/15

If I move a block above another block, the one that isn't moved gets its CKEditor field duplicated. If you do it again, you get it a third time etc!
<img width="700" alt="Screenshot 2024-02-27 at 12 56 56" src="https://github.com/verbb/vizy/assets/1942313/f9e2f778-206d-449f-927e-cf942fdba89f">

### Steps to reproduce

1. Create two blocks that have a CKeditor field in them
2. Re-order them

### Craft CMS version

4.8.0

### Plugin version

2.1.15

### Multi-site?

No

**Comment by engram-design** [comment]
Yep, just another instance of jQuery vs Vue handling we have to cater for. Fixed in [2.1.16](https://github.com/verbb/vizy/releases/tag/2.1.16)
