### ISSUE TITLE
[Craft 5] Block fields not saving

### ISSUE THREAD

**Issue by bryce-pod1** [verbb/vizy#286]
### Describe the bug

On saving a Vizy field, block fields are not saved, just empty group tabs are left.

### Steps to reproduce

1. Create Vizy field and name it.
2. Save field to enable adding of blocks (bug or intended?)
3. Add block group and name it.
4. Drag field into group (I tried multiple fields types.)
5. Save field.
6. Field is nolonger in group.

### Craft CMS version

5.0.0-beta.6

### Plugin version

3.0.0-beta.2

### Multi-site?

No

**Comment by engram-design** [comment]
Just note that the block type configuration won't appear due to a [Craft bug](https://github.com/craftcms/cms/pull/14526) which should be fixed for upcoming betas.

Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-5 as 3.0.0-beta.2"`.
