### ISSUE TITLE
[Craft 5] Unable to use matrix fields

### ISSUE THREAD

**Issue by d-karstens** [verbb/vizy#292]
### Describe the bug

Hi,

After upgrading to Craft 5 we've encountered this issue with Vizy blocks containing matrix field

When trying to add a block to content we get the following message 
![Screenshot 2024-03-28 at 11 21 00 am](https://github.com/verbb/vizy/assets/21274925/2eb0ae2f-9d14-444c-89e0-f0dbb467324d)

And this error happens when trying to save the entry, or when trying to access an old entry that had the block before migrating
![Screenshot 2024-03-28 at 11 19 53 am](https://github.com/verbb/vizy/assets/21274925/b418c1fa-a53c-46da-a721-7fb80f7d88f8)

### Steps to reproduce

1. Create a block with a matrix field
2. Try to add the block to a new entry

### Craft CMS version

5.0.0

### Plugin version

3.0.0-beta.4

### Multi-site?

No

**Comment by engram-design** [comment]
Now this is going to be tricky, and we've known about this for a little bit. But basically, Matrix fields' new behaviour is that it relies on a parent element for a lot of things. In a normal scenario, this would be the owner entry, or a parent Matrix block. But as this is connected with a Vizy block, which isn't an element (and isn't saved as one due to performance), this makes it impossible to use Matrix fields and other element-like fields (addresses) with Vizy.

We're obviously looking for solutions to this!

**Comment by engram-design** [comment]
Should be fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-5 as 3.0.0-beta.4"`.

**Comment by d-karstens** [comment]
Thanks! 
Matrix fields appear to be working now, but have encountered another issue when trying to save Vizy blocks containing Hyper fields - posting here as it seems to have started happening after applying that update (confirmed this by downgrading and testing again)

Let me know if you need more details

<img width="1234" alt="Screenshot 2024-04-02 at 9 28 31 AM" src="https://github.com/verbb/vizy/assets/21274925/eee97327-54d9-4e86-ae91-4c16dcfb45fe">
<img width="1223" alt="Screenshot 2024-04-02 at 9 28 41 AM" src="https://github.com/verbb/vizy/assets/21274925/af0377d9-8edb-40bf-9a34-4dc95b2bf048">

**Comment by engram-design** [comment]
Should be fixed (again) for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-5 as 3.0.0-beta.4"`.

**Comment by engram-design** [comment]
Fixed in [3.0.0-beta.5](https://github.com/verbb/vizy/releases/tag/3.0.0-beta.5)

**Comment by clebuchegger** [comment]
hi!
for me matrix field also don't work, I get the following error when trying to add a block:

"Invalid owner ID: 506189594"
![Bildschirmfoto 2024-06-19 um 09 04 01](https://github.com/verbb/vizy/assets/4832515/37ad69b4-b593-4a56-89df-7978a65ddb44)

the response:
![Bildschirmfoto 2024-06-19 um 08 59 26](https://github.com/verbb/vizy/assets/4832515/9d0474b8-ca02-4caf-8d12-563a7a4ea04c)


using:
craft 5.2.2
vizy 3.0.0-beta.5

**Comment by engram-design** [comment]
Can you let me know what "View Mode" the Matrix field is set to? Vizy only supports "As inline-editable blocks".

**Comment by bleepsandblops** [comment]
FYI it looks like having super table fields within a Vizy block (that were then converted to matrix) wiped out all the content within those fields... Getting that "entries can only be saved" message then whether i save or discard changes, the content is gone.

**Comment by engram-design** [comment]
Ah, I see @bleepsandblops this might need to be a separate issue when it comes to Super Table and Vizy. Likely, I might need to add some handling to Super Table's migration for Vizy.
