### ISSUE TITLE
[Craft 4.x]: Images with id string in attributes failing to render

### ISSUE THREAD

**Issue by anita-chouhan** [verbb/vizy#293]
### Describe the bug

We recently upgraded our Craft CMS version to 4.7.2 from 3.8.17. We are using a _vizy_ field in the project and found that some of the entries having an image inside the rich text are failing to render. The error is showing as:

<img width="948" alt="Screenshot 2024-03-29 at 3 12 27 PM" src="https://github.com/verbb/vizy/assets/30666052/795b01cf-558d-4367-8eed-554cf5bf76e9">

### Steps to reproduce

1. Setup a Craft CMS version 3.8.17 with a _vizy_ field
   Field Settings:
     - Editor Config: Default
     - Editor Mode: Blocks & Rich Text
     - Remove Empty Paragraphs: True
     - Plain Text Paste: False
     - Block Type Picker Behaviour: Click
2. Add some entries with images and text.
3. Upgrade the Craft CMS version to 4.7.2

### Craft CMS version

4.7.2

### Plugin version

2.1.17

### Multi-site?

No

### Additional context

We observed that the issue is resolved if:
- Cut the entire field content.
- Paste it back.
- Re-save the entry.

We compared the database output of both the working and non-working versions of the entries and found that the non-working version has an `Id` parameter inside the `attrs` array which is absent in the working version of the entry.

**Working Version**
<img width="961" alt="Screenshot 2024-03-29 at 2 21 00 PM" src="https://github.com/verbb/vizy/assets/30666052/914ebcde-29bb-4f5c-bf49-5cc0d1923721">

**Non-working Version**
<img width="953" alt="Screenshot 2024-03-29 at 2 21 11 PM" src="https://github.com/verbb/vizy/assets/30666052/8e4613ad-f48a-4ca9-aa54-ee13486166cc">

**Comment by engram-design** [comment]
Hmmm, it seems strange that the `embed115` ID was there as an attribute, that shouldn't have been possible. But, I can certainly add handling for that.

Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.17"`.

**Comment by anita-chouhan** [comment]
@engram-design Thank you for providing the fix. The entries are loading fine now after updating the plugin.
