### ISSUE TITLE
Asset field 'Upload a file' gets duplicated when moving blocks

### ISSUE THREAD

**Issue by bleepsandblops** [verbb/vizy#295]
### Describe the bug

Probably related to #284:
<img width="391" alt="Screenshot 2024-04-18 at 22 26 34" src="https://github.com/verbb/vizy/assets/1942313/21179b72-3488-425c-bb23-fda894a39691">

### Steps to reproduce

1. Add two vizy blocks, the first one containing an asset field
2. Move the other block above that first one
3. The 'upload a file' button gets duplicated as in screenshot

### Craft CMS version

4.8.9

### Plugin version

2.1.18

### Multi-site?

No

### Additional context

Client also says some asset fields and CKEditor fields get *emptied* as they work on the page but I can't reproduce yet

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.18"`.

**Comment by engram-design** [comment]
Fixed in [2.1.19](https://github.com/verbb/vizy/releases/tag/2.1.19)
