### ISSUE TITLE
Links get mangled when pasting from a CKEditor field to a Vizy field

### ISSUE THREAD

**Issue by bleepsandblops** [verbb/vizy#297]
### Describe the bug

When copy pasting from a CKEditor field to a Vizy field with Blocks & Rich text, the position of the links in the text change, cf below:

The CKEditor field:
<img width="856" alt="Screenshot 2024-04-25 at 14 35 28" src="https://github.com/verbb/vizy/assets/1942313/2af55d10-9b9f-4ebe-94fb-81def8528974">

Pasting into Vizy field that has blocks & rich text enabled:
<img width="834" alt="Screenshot 2024-04-25 at 14 35 39" src="https://github.com/verbb/vizy/assets/1942313/547f746b-0dd0-4d61-a17f-e7e30a0efc55">

Aware we can plain text paste but the client would like to retain the links here.

Thank you!

### Steps to reproduce

1. Copy from a CKeditor field
2. Paste into a Vizy field with Rich blocks & Text

### Craft CMS version

4.8.9

### Plugin version

2.1.18

### Multi-site?

No

**Comment by engram-design** [comment]
I've just been testing this, and I can't seem to replicate it! Could you paste here the raw (in a code block) HTML from CKEditor?

**Comment by engram-design** [comment]
Ah, actually just got this to replicate. Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.18"`.

**Comment by engram-design** [comment]
Fixed in [2.1.19](https://github.com/verbb/vizy/releases/tag/2.1.19)
