### ISSUE TITLE
Empty fields are evaluating as `<p></p>`

### ISSUE THREAD

**Issue by furioursus** [verbb/vizy#30]
**Description**
When a Vizy field is left empty on an entry, it renders `<p></p>` when called in a template. This isn't really desirable behavior, as it means I can't use a simple conditional like `{% if entry.vizyField | length %}` to skip rendering it. Instead I need to write something like `{% if block.heading != '<p></p>' and block.heading != "" %}{% endif %}` which isn't necessarily the end of the world, but it seems a bit clunky to have to keep evaluating it over and over, depending on where all I use it.

**Steps to reproduce**
1. Create a simple Vizy field with no buttons or formatting, just a basica paragraph field.
2. Render the field in the template and feed it through a standard conditional to test for length.

**Additional info**
- Plugin version: 1.0.1
- Craft version: 3.6.15
- Multi-site: No

**Additional context**
For added bonus, try running it through a plugin that makes changes to strings like Retcon:
```twig
{% if block.heading %}
  {{ block.heading | retcon([
    ['change', 'p', 'h2'],
    ['attr', 'h2', { class: 'text-center text-xl md:text-3xl mb-12 text-sec-gray-400' }]
  ])}}
{% endif %}
```
Because there's an empty node in there, other plugins give up and throw errors.

**Edit**
Realizing that this might be sort of a duplicate or at least tangent of #25, so feel free to prune or remove as necessary and I'll join in over there, instead.

**Comment by engram-design** [comment]
Good point, I think for this case, a completely empty field, it should respect that, regardless of the solution in https://github.com/verbb/vizy/issues/25 which is much more geared to empty paragraphs within content.

Fixed for the next release. To get the fix early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-3 as 1.0.2",
  "...": "..."
}
```

Then run `composer update`.

**Comment by furioursus** [comment]
Fantastic. Should I be able to evaluate an empty field like `{% if entry.vizyFieldHandle | length %}`?

**Comment by engram-design** [comment]
Correct, yep.

**Comment by engram-design** [comment]
Fixed in [1.0.3](https://github.com/verbb/vizy/releases/tag/1.0.3)

**Comment by bleepsandblops** [comment]
This seems to not be working in 1.0.9
`{{ entry.vizyField.query().count() }} gives me 5`
but
`{{ entry.vizyField | length }} is 0`

**Comment by engram-design** [comment]
Fixed for the next release. To get the fix early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-3 as 1.0.9",
  "...": "..."
}
```

Then run `composer update`.
