### ISSUE TITLE
Re-ordering existing assets will not be saved

### ISSUE THREAD

**Issue by holiday-jan** [verbb/vizy#300]
### Describe the bug

When we re-order existing assets in vizy, the new order won't be saved.

### Steps to reproduce

1. Add multiple assets (2 is enough)
2. Save
3. Re-order assets (switch them, drag-and-drop)
4. Save
5. Reopen, old order is back

### Craft CMS version

4.9.3

### Plugin version

2.1.19

### Multi-site?

No

### Additional context

Reverted back to Vizy 2.1.18, re-ordering works, so should only be a bug in the latest version

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.19"`.

**Comment by holiday-jan** [comment]
works, thank you!

**Comment by engram-design** [comment]
Fixed in [2.1.20](https://github.com/verbb/vizy/releases/tag/2.1.20)
