### ISSUE TITLE
Craft 5 side panel bug - Craft.Vizy.Input is not a constructor

### ISSUE THREAD

**Issue by bleepsandblops** [verbb/vizy#304]
### Describe the bug

In the Entries view, double click on the status dot (in this case, green) to open the side-pane. 
An entry with some Vizy fields loads fine. 

Close by clicking on Discard changes (see #287 if related) or Cancel, it closes fine.
Now re-open that entry in the same way, and the Vizy fields don't load
<img width="542" alt="Screenshot 2024-07-26 at 16 26 47" src="https://github.com/user-attachments/assets/9e58fa4e-72c3-4fae-be3a-5a923a8c8dca">

and you get this in the console:
Craft.Vizy.Input is not a constructor
<img width="508" alt="Screenshot 2024-07-26 at 16 24 24" src="https://github.com/user-attachments/assets/d288a00b-488c-42da-bba9-0c018c58600e">

### Steps to reproduce

See above

### Craft CMS version

Craft Pro 5.2.8

### Plugin version

3.0.1

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-5 as 3.0.1"`.

**Comment by engram-design** [comment]
Fixed in [3.0.2](https://github.com/verbb/vizy/releases/tag/3.0.2)
