### ISSUE TITLE
Preview mode deletes the content of a CKEditor field

### ISSUE THREAD

**Issue by bleepsandblops** [verbb/vizy#306]
### Describe the bug

Please see video below:
https://github.com/user-attachments/assets/a954ecf1-86f2-4097-9469-9342a9ac8572

If you go into preview mode and just click within your CKEditor field, the field content disappears on the right-hand pane, still shows up on the edit pane but is actually gone. If you click on the close preview mode you go back to the main entry page with the text of the field gone.

### Steps to reproduce

See above

### Craft CMS version

5.2.9

### Plugin version

3.0.1

### Multi-site?

No

### Additional context

CKEditor 4.1.0

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-5 as 3.0.1"`.

**Comment by engram-design** [comment]
Fixed in [3.0.2](https://github.com/verbb/vizy/releases/tag/3.0.2)
