### ISSUE TITLE
Deleting a matrix block within a custom vizy block doesn't seem to take affect

### ISSUE THREAD

**Issue by zhua89cc** [verbb/vizy#308]
### Describe the bug

Deleting or disabling a matrix block that is being used in a custom vizy block is not taking affect. Removing it and then resaving the entry doesn't seem to actually remove it.

It seems the json content of my vizy field is not reflecting the removal of a matrixblock that is being used in a custom vizy block. I believe this is a vizy issue because adding the matrix field to the entry level itself works as expected. (Deleting and disabling)

Here is an embedded loom video showing the issue

https://www.loom.com/share/88f6d15f7fd64d41a95abfce4a8084fe?sid=0bc2f758-df85-476a-9164-33134cc4159d

<div style="position: relative; padding-bottom: 57.50798722044729%; height: 0;"><iframe src="https://www.loom.com/embed/88f6d15f7fd64d41a95abfce4a8084fe?sid=6ee4ed71-6609-422f-ba93-ea5c541f4edc" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe></div>

### Steps to reproduce

1. Create a custom vizy block that uses a matrix field in a vizy field
2. On an entry that has the vizy field add that custom vizy block and add a few matrix blocks. Try disabling or deleting a matrix block. On save and after the cp page reloads the matrix block is still here.

### Craft CMS version

4.11.1

### Plugin version

2.1.20

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.20"`.

**Comment by zhua89cc** [comment]
Thanks for the swift response as always @engram-design

**Comment by engram-design** [comment]
Fixed in [2.1.21](https://github.com/verbb/vizy/releases/tag/2.1.21)
