### ISSUE TITLE
Customising table markup?

### ISSUE THREAD

**Issue by tomkiss** [verbb/vizy#311]
### Question

How can I customise the output for an HTML table?

### Additional context

I'm trying to customise the output for an HTML table.

What I'd like to do, in order to create a collapsing table in CSS, is to add some extra properties to the markup.

So, for example, this:

```html
<tr>
  <td>Pear<td>
  <td>Fruit<td>
</tr>
```

Would become something like this:

```html
<tr>
  <td data-value="Pear">Pear<td>
  <td data-value="Fruit">Fruit<td>
</tr>
```
Or, similar markup. 

It looks like the `TableCell` node type isn't output as part of a `node in vizyArticle.all()` loop. I can see a `Table` node type output - so I assume I have to traverse the contents of a Table node and re-markup the output.

fyi I had initially tried something like this:
```twig
{%- for node in vizyArticle.all() -%}
  {# (some other logic previously) #}
  {{node.renderHtml({
      tableCell: {
          attrs: {
              data: {
                  test: 'test'
              }
          },
      },
  })}}
{%- endfor -%}
```
But that results in an error, because it's a node and can't take a config object like that (which makes sense, but was a little surprising).

Anyway, is there any other way to customise the table markup? What would the correct approach be here?

**Comment by engram-design** [comment]
If you want to go the complete custom render route, you can follow similar to the below:

```twig
{% for node in entry.vizyField.all() %}
    {% if node.type == 'table' %}
        <table>
            <tbody>
                {% for tableRow in node.content %}
                    <tr>
                        {% for tableColumn in tableRow.content %}
                            <td>
                                {% for tableNodes in tableColumn.content %}
                                    {{ tableNodes.renderHtml() }}
                                {% endfor %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endfor %}
```

Don't forget you also have access to `tableRow.tagName` and `tableRow.attrs` for things like `tr` if you want to keep things dynamic, or use the Craft `{{ tag() }}` function to keep things less HTML-y.

As for using the config options to just modify attributes, that's not strictly possible, but with some modifications on my end:

```twig
{{ entry.vizyField.renderHtml({
    table: {
        attrs: {
            data: {
                test: 'test-table',
            },
        },
        nodes: {
            tableRow: {
                attrs: {
                    data: {
                        test: 'test-row',
                    },
                },
                nodes: {
                    tableCell: {
                        attrs: {
                            data: {
                                test: 'test-cell',
                            },
                        },
                    },
                },
            },
        },
    },
}) }}
```

Which I know is a lot, but that's two options. We don't allow for nested nodes to be defined at the top level.

Updated for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.22"`.

**Comment by tomkiss** [comment]
Amazing, thank you Josh - super helpful, as always! 🙌
