### ISSUE TITLE
Custom entry sources not showing up in link to entry selection modal

### ISSUE THREAD

**Issue by f-elix** [verbb/vizy#312]
### Describe the bug

When creating a link to an entry, custom sources are not showing up.

### Steps to reproduce

1. Create a custom source 
2. In a Vizy field, create a link and select "Link to an entry"
3. Custom sources are not visible

### Craft CMS version

5.4.3

### Plugin version

dev-craft-5 as 3.0.3

### Multi-site?

Yes

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-5 as 3.0.3"`.

**Comment by f-elix** [comment]
Thanks for the quick fix! Just saw this as well https://github.com/verbb/vizy/issues/226, can be closed with this one.

**Comment by engram-design** [comment]
Fixed in [3.0.4](https://github.com/verbb/vizy/releases/tag/3.0.4)
