### ISSUE TITLE
On keystroke inserting HyperLink Causes Modal to Flash

### ISSUE THREAD

**Issue by zhua89cc** [verbb/vizy#315]
### Describe the bug

This works in that inserting a hyperlink in a vizy saves it to the json blob to be saved to the db seemingly. There does seem to be a console error on keydown that is causing the modal to flash on each keystroke. Please see screenshot of console error and loom from stakeholder of it flashing. 

https://www.loom.com/share/5204ab49439a42c0ab4674a11f158b31

<img width="1233" alt="Screenshot 2024-10-08 at 11 17 10 AM" src="https://github.com/user-attachments/assets/982da7f8-3223-4fbe-af13-a3d99d2fcab8">

### Steps to reproduce

1. Select some text to add a URL to. 
2. Click the link button in the toolbar
3. select insert link
4. start typing the url into the field 

### Craft CMS version

4.12.3

### Plugin version

2.1.22

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-4 as 2.1.22"`.

**Comment by engram-design** [comment]
Fixed in [2.1.23](https://github.com/verbb/vizy/releases/tag/2.1.23)
