### ISSUE TITLE
Page crashes when adding a block containing a Hyper field

### ISSUE THREAD

**Issue by f-elix** [verbb/vizy#318]
### Describe the bug

I have a Vizy field which has several different blocks, some of which contain a Hyper field. Everything was working well with all the latest plugin versions. But now whenever I add a block that has a Hyper field in the Vizy field, the page becomes unresponsive and an OOM error occurs (error code 5 in Chrome). I inspected the network and console tabs while reproducing the bug and I can't see any logs or errored network requests.

I'm using Hyper v2.1.2

I'm not sure if this is a Vizy or Hyper bug.

### Steps to reproduce

1. Create a Vizy field
2. Define a block with a Hyper field in the Vizy field config
3. Create an entry with the Vizy field and add the block
4. The page crashes

### Craft CMS version

5.4.8

### Plugin version

3.0.4

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/vizy:"dev-craft-5 as 3.0.4"`. See https://github.com/verbb/hyper/issues/179#issuecomment-2405403497

**Comment by f-elix** [comment]
Thank you!
