### ISSUE TITLE
Easier and better collapse

### ISSUE THREAD

**Issue by magnusskogen** [verbb/vizy#32]
Would be great to be able to collapse/expand blocks with one click instead of two. Today you have to click the gear icon and then collapse menu item. This functionality is so useful that it could have a button icon by itself. Also double clicking the block bar should collapse/expand the block, just as in Matrix.

**Comment by engram-design** [comment]
Not sure I agree about having it as an icon on the same level as the enable/disable or move functions. The reason being - we can't feasibly have **all** these items at the top level of the UI for the block, which would just get cluttered. I'll consider it though.

Double clicking on the block header is achievable for sure - didn't even realise that was a thing for native Matrix!

**Comment by magnusskogen** [comment]
Also being able to see a better preview of the block in collapsed mode would be nice, maybe by choosing what fields that will be part of the collapsed preview in the field editor. Here are my five cents.

<img width="612" alt="Skjermbilde 2021-05-31 kl  11 43 43" src="https://user-images.githubusercontent.com/32260868/120174753-bc9d9100-c205-11eb-8690-e0af229c7d05.png">

**Comment by scandella** [comment]
Double-clicking on the block header, just like it works for a Matrix block should be the standard behavior, even Neo has it!

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0)
