### ISSUE TITLE
Copy pasting a formatted content into Vizy would lose its formatting

### ISSUE THREAD

**Issue by yonatangdev** [verbb/vizy#320]
### Describe the bug

For example, after copying an unordered list and pasting that into Vizy would result in all the items in the list in one line without any formatting.

![image](https://github.com/user-attachments/assets/47db2d17-6028-40f0-b028-ceedc6241234)

The list is where I copied it from and the line you see below is when I paste the same content back.

### Steps to reproduce

1. copy a formatted content from Vizy itself or another location
2. Paste it back but it loses the format.

### Craft CMS version

4.12.8

### Plugin version

2.1.23

### Multi-site?

Yes

**Comment by engram-design** [comment]
Strange, I certainly can't replicate that. Do you have the "Plain Text Paste" field setting enabled?

**Comment by yonatangdev** [comment]
Sorry. It was Plain Text Paste setting.
