### ISSUE TITLE
Error in Craft 5.5.0.1

### ISSUE THREAD

**Issue by tomkiss** [verbb/vizy#322]
### Describe the bug

Seeing an error since upgrading to Craft [5.5.0.1](https://github.com/craftcms/cms/releases/tag/5.5.0.1).

Seeing:

```
Call to undefined method verbb\\vizy\\models\\BlockType::defaultCardAttributes()
```

In both front end templates and the control panel when trying to load Field Types page, or edit a Vizy field config.

### Steps to reproduce

1. Have Vizy installed on a craft instance 5.X instance but not > 5.5
2. Ensure a Vizy field is configured
3. Upgrade to 5.5.0.1
4. Try to load the Field Types panel in the CP, or edit the field from an Entry Type
5. Observe the error in the browsers dev panel

### Craft CMS version

5.5.0.1

### Plugin version

3.0.4

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [3.0.5](https://github.com/verbb/vizy/releases/tag/3.0.5)
