### ISSUE TITLE
Nested vizy field disappears after first save

### ISSUE THREAD

**Issue by dGilli** [verbb/vizy#33]
**Description**
Vizy field inside a matrix inside a vizy block disappears after saving.

**Steps to reproduce**
1. Nested vizy field (vizy -> matrix -> vizy)
2. After saving the nested vizy field is no longer displayed

**Additional info**
- Plugin version: 1.0.2
- Craft version: 3.6.15
- Multi-site: Yes

**Comment by engram-design** [comment]
Fixed in [1.0.5](https://github.com/verbb/vizy/releases/tag/1.0.5)
