### ISSUE TITLE
"Unsaved changes" prompt even if nothing was changed

### ISSUE THREAD

**Issue by dGilli** [verbb/vizy#34]
**Description**
Unsaved changes triggered just by clicking into a text field

**Steps to reproduce**
1. Open existing entry w/ vizy field
2. Click to focus text in field
3.  Trying to navigate away will prompt with unsaved changes.

**Additional info**
- Plugin version: 1.0.2
- Craft version: 3.6.15
- Multi-site: Yes

**Additional context**
Observed in Browser: Firefox Developer 89.0b15 (64-bit)

**Comment by magnusskogen** [comment]
Experiencing the same behaviour.

**Comment by engram-design** [comment]
Can't replicate this one sorry. Can you confirm your field setup, if you're talking about a Vizy Block, and if so, what fields?

I've tested with a plain text field in a Vizy Block (single level), as well as a nested Vizy field with the same setup.

**Comment by engram-design** [comment]
Closing due to age. If anyone is still experiencing this, please use https://github.com/verbb/field-manager to export the field, and send here, with a screenshot of your content for an entry that shows this issue.
