### ISSUE TITLE
"Select all" inside a nested Vizy-field selects the whole Vizy field

### ISSUE THREAD

**Issue by magnusskogen** [verbb/vizy#39]
**Description**
When trying to "Select all" text inside a nested Vizy-field all the content of the main Vizy field is selected. Copying what is selected returns the json object for the main field.

**Steps to reproduce**
1. Create a Vizy field inside a Vizy field.
2. Add some content.
3. Try to select all text inside the field (cmd + a)

**Additional info**
- Plugin version: 1.0.2
- Craft version: 3.6.15
- Multi-site: Yes or No

**Additional context**

**Comment by engram-design** [comment]
Yep, a known issue I need to figure out with ProseMirror and selection-handling.

**Comment by engram-design** [comment]
Just to clarify on this - when using "select all" (command/control + A) this should only select child nested fields, not the other way around. For instance, if you select all on the top-level Vizy field or block, it should select the child field/block, but not the other way around. Doing a select all on a child field/block shouldn't be selecting the parent - at least that's not what I'm seeing.

If you're still having this issue, are you able to send through a short video recording of it in action?

**Comment by engram-design** [comment]
Fixed in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0)
