### ISSUE TITLE
Not all field in matrix are saved

### ISSUE THREAD

**Issue by wmdhosting** [verbb/vizy#42]
**Description**
JUst info..  Have some matrix field with many settings
and some just dont get saved .. after entry save.

But allways get first setting after save. or soem not working.. 

**Steps to reproduce**
1.![Snag_2ba10d5](https://user-images.githubusercontent.com/76176291/120660321-7f483600-c487-11eb-8d35-7d09ccb45b80.png)
2. Or some text fields. with settings

**Additional info**
Vizy 1.0.2
Craft Pro 3.6.16

**Comment by engram-design** [comment]
Not sure I understand the issue, sorry! I can't seem to identify the field you'd pointing to, is this an assets field?

You might want to update to [1.0.5](https://github.com/verbb/vizy/releases/tag/1.0.5) as well.
