### ISSUE TITLE
Add menu of CSS classes like the formatting menu

### ISSUE THREAD

**Issue by weotch** [verbb/vizy#44]
**What are you trying to do?**
Add a menu for adding CSS classes or customizing the formatting options with CSS classes.  Our use case is decoupling the styling of elements from the HTML tag used for better accessibility and SEO handling.  For instance, we may want to render text large but don't necessarily want the tag to be an H1.

**What's your proposed solution?**
I'd love a seperate pulldown menu of CSS classes like how formatting options is implemented.  The styling of those classes could supplied as part of the configuration file or maybe stored in a CSS file that is loaded from a special location, like /web/vizy.css.

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0). Have a read through the [blog post](https://verbb.io/blog/vizy-2-1), the [extensibility docs](https://verbb.io/craft-plugins/vizy/docs/template-guides/extending-vizy) and the [user guides](https://verbb.io/craft-plugins/vizy/docs/user-guides)
