### ISSUE TITLE
[Feature Proposal] Allow nesting same Vizy field recursively

### ISSUE THREAD

**Issue by benface** [verbb/vizy#45]
**What are you trying to do?**
I would like to have a single Vizy field for everything. Some block types, such as “Row with X columns", should ideally accept the same content that the root does, so I’d rather not create another Vizy field with the same settings. It would be nice if we could use the Vizy field we’re currently working on as a field for a block type in the very same field.

**What's your proposed solution?**
I’ve tried creating two Vizy fields with the same settings, except that the “Row with X columns” block has the other field (so in Field A, the block has Field B, and in Field B, it has Field A). That doesn’t work: any form that contains one of the two fields loads indefinitely, and eventually times out. I am strongly suspecting an infinite recursion issue. I realize this is a real challenge for this suggestion, but I think it’s worth the effort. Perhaps there could be a maximum nesting level? 10 should be way more than enough.

Thank you for your consideration!

**Comment by engram-design** [comment]
So I've started my own experimentation here, and it _should_ be possible with some careful consideration. As you say, we'll hit an infinite loop at some point when trying to load the blocktypes for all the fields within the Vizy field.

**Comment by JshGrn** [comment]
> So I've started my own experimentation here, and it _should_ be possible with some careful consideration. As you say, we'll hit an infinite loop at some point when trying to load the blocktypes for all the fields within the Vizy field.

This will be a game changer for me tbh

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0)
