### ISSUE TITLE
Add "collapse all" and "expand all" buttons

### ISSUE THREAD

**Issue by davidsprinz** [verbb/vizy#5]
Just a small improvement, but when having a lot of blocks, two buttons for "collapsing all blocks" / "expanding all blocks" at a single click would be convenient (like the [Matrix Toolbar plugin](https://plugins.craftcms.com/matrixtoolbar) does it).

**Comment by engram-design** [comment]
I'm all for this feature, but having extra buttons like the Matrix Toolbar does isn't ideal for me personally - but that's just looks. If we were to implement this, we'd likely add it to the settings dropdown (alongside "Collapse"/"Expand") to include "Collapse All"/"Expand All".

I've also often found the process of clicking multiple checkboxes and then collapsing even native Matrix blocks to be pretty tedious in practice. All that clicking and you might as well be collapsing one-by-one.

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0)
