### ISSUE TITLE
FR: Easy tables

### ISSUE THREAD

**Issue by bartrylant** [verbb/vizy#57]
**What are you trying to do?**
It would be cool if there was a very easy way of making tables in a vizy field. I know I could use the table maker plugin and add it as a block, but for most clients that's a bit of overkill (first defining the number of columns, giving them all a header,…).

I don't know if the vizy text field is based on Redactor or CKeditor? For both, there are plugins available. The Redactor table plugin is a bit cumbersome as it adds a button with lots of text descriptions. The CKeditor table button is great: you can select a number of rows and columns, combine cells, add columns,...

**Comment by engram-design** [comment]
On my list to do. Vizy is based on [tiptap](https://www.tiptap.dev/) which fortunately has a [table](https://www.tiptap.dev/examples/tables) node. As you can see from the demo, there's a good amount of UX/UI to sort out, but the functionality is all there.

So expect this sooner rather than later!

**Comment by danleecpi** [comment]
@engram-design I noticed adding a table in the code view that it gets stripped out and converted to paragraphs currently. Will the table node solve this?

We would be using Tailwind's formatting for the table when contained in the 'prose' class. See their [table styles](https://tailwindcss-typography.netlify.app/) in the demo at the end of the page.

**Comment by engram-design** [comment]
That’s correct, we need proper support for table markup through a table node.

**Comment by danleecpi** [comment]
Wonderful - when do you think it would be possible to include this into the plugin?

**Comment by engram-design** [comment]
No ETA I'm afraid, as I'm prioritising some annoying bugs at the moment, before addressing new features.

**Comment by anchovy** [comment]
Hi @engram-design any update to this, we'd love to be able to use this feature.

**Comment by tin-soldier** [comment]
+1. Highly needed.

**Comment by Loran35** [comment]
+1 Highly needed too for a migration from an other cms with table tags in html content.

**Comment by maxstrebel** [comment]
+1 from me. No good alternative in sight 😉

**Comment by leevigraham** [comment]
To add to the original comment… The table maker plugin doesn't easily allow links in cells.

**Comment by JshGrn** [comment]
Where is this one in the priority queue, is it still on the back burner?

**Comment by engram-design** [comment]
@JshGrn Should have this completed very soon.

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0)
