### ISSUE TITLE
Renaming Field that is used in Vizy causes an UnknownPropertyException

### ISSUE THREAD

**Issue by internetztube** [verbb/vizy#6]
Thanks for this plugin. It simplifies our workflow enormously! 
I noticed a bug while testing it.

**Description**

```
vendor/yiisoft/yii2/base/BaseObject.php: 


Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: craft\behaviors\CustomFieldBehavior::fieldName
```

**Steps to reproduce**
1. Create a Vizy Field
2. Create a field with name "test-field1"
3. Use "test-field1" in Vizy Field
4. Create Entry with the Vizy Field in it and add a "test-field1" block
5. Rename "test-field1" to "test-field-2"
6. Try to edit the Entry that you save a few moments ago

**Additional info**
- Plugin version: 1.0.0
- Craft version: Craft Pro 3.6.12
- PHP: 7.3.27
- Multi-site: Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get the fix early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-3 as 1.0.0",
  "...": "..."
}
```

Then run `composer update`.

**Comment by internetztube** [comment]
Thank you!

**Comment by internetztube** [comment]
This issue is still not resolved.

**Comment by engram-design** [comment]
Are you getting the exact same issue? My testing shows no errors are thrown when changing the field handle.

**Comment by internetztube** [comment]
Odd. Now it works. Thanks!
