### ISSUE TITLE
Add classname attribute to Link

### ISSUE THREAD

**Issue by jmchat** [verbb/vizy#65]
**What are you trying to do?**
A description of what you want to happen.
Currently you can not give a link a classname when you open the the link pop-up. this can be useful to give some special stying to a link.

**What's your proposed solution?**
A description of how you think this could be solved, including any alternatives that you considered.
Please add the classname attribute to the current attributes, see: 
https://verbb.io/craft-plugins/vizy/docs/developers/mark#link

**Additional context**

**Comment by engram-design** [comment]
Currently, the only way to handle this is through [custom rendering config](https://verbb.io/craft-plugins/vizy/docs/template-guides/modify-nodes):

```
{{ entry.vizyField.renderHtml({
    paragraph: {
        marks: {
            link: {
                merge: true,
                attrs: {
                    class: 'text-blue-500',
                },
            },
        },
    },
}) }}
```

We'll look at adding something customisable in the field, for each link.

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0)
