### ISSUE TITLE
Space Insertion Edge Case?

### ISSUE THREAD

**Issue by kerns** [verbb/vizy#66]
**Description**
Not sure if this is a bug or just a quirk I need to handle by trimming the output. But in this instance the last word `Autofarm` has italics applied to the word but not the punctuation. A space is inserted at some point in the assembly process.

**Additional info**
- Plugin version: 1.0.5
- Craft version: 3.7xxx
- Multi-site: No

**Additional context**

<img width="604" alt="Screen Shot 2021-08-12 at 13 29 36" src="https://user-images.githubusercontent.com/20254/129212272-061c7457-79f3-4cea-a9f9-9e239abaeb04.png">
<img width="592" alt="Screen Shot 2021-08-12 at 13 28 50" src="https://user-images.githubusercontent.com/20254/129212276-348be13b-6d17-4ca7-a496-f6b2e401cd3b.png">
<img width="849" alt="Screen Shot 2021-08-12 at 13 29 05" src="https://user-images.githubusercontent.com/20254/129212278-eb0bb33e-8fdc-4329-bd36-f38d12b5fa04.png">

**Comment by engram-design** [comment]
Shouldn't be something you need to handle, that's strange behaviour. I can't seem to immediately replicate it on my end.

![image](https://user-images.githubusercontent.com/1221575/131234061-e4eed854-5bae-4191-8850-169cd6567f7a.png)

![image](https://user-images.githubusercontent.com/1221575/131234069-dbcd9acb-c50c-4adf-93e4-d6590ac18bf8.png)

**Comment by bavocorteville** [comment]
Had a similar problem. A link followed by text in bold resulted in removing the space between them. My issue was solved by removing the spaceless tag in my code.

**Comment by engram-design** [comment]
Can't seem to replicate this (again). Are you able to send through the column for the element and Vizy field?

Go to `content` in your database, and filter the `elementId` by the entry that you were adding content for the Vizy field to. Find the column `field_myVizyField_xxxxxx` and send through the JSON in that column.

**Comment by bavocorteville** [comment]
`[{"type":"paragraph","attrs":{"textAlign":"start"},"content":[{"type":"text","text":"Github "},{"type":"text","marks":[{"type":"bold"}],"text":"Vizy"},{"type":"text","text":" "},{"type":"text","marks":[{"type":"italic"}],"text":"test"}]}]`

![image](https://user-images.githubusercontent.com/2085698/147915831-19a69687-282d-4879-82fa-6502bda7338f.png)
![image](https://user-images.githubusercontent.com/2085698/147915856-eff03bfb-ac3b-4304-9e94-35744270d7ef.png)
![image](https://user-images.githubusercontent.com/2085698/147915872-422c6037-4f72-4832-9bed-8acf7cadc4ff.png)

**Comment by engram-design** [comment]
Ah, I did miss you saying you're using the `{% spaceless %}` Twig tag - I'm not sure if @kerns is also using that. That's a tricky situation, and is kind of how that Twig tag works, removing spaces from HTML.

Using just raw Twig (without Vizy involved at all) take the following HTML examples.

```
<p>Github <strong>Vizy</strong> <em>test</em></p>
```

Produces: Github **Vizy** _test_

```
{% apply spaceless %}
    <p>Github <strong>Vizy</strong> <em>test</em></p>
{% endapply %}
```

Produces: Github **Vizy**_test_

I'm not sure if there's anything we can do about that, as that's just how Twig's `spaceless` filter works. It's curious that it doesn't remove the space between `Github <strong>` but it likely looks at two tags `</strong> <em>` and applies that.

In addition, this exact issue happens with other rich text editors (Redactor, CKEditor), so it's not a problem unique to Vizy. As such, closing for the moment (unless @kerns original issue is different, not using the `spaceless` filter).
