### ISSUE TITLE
Add support for superscript and subscript extensions

### ISSUE THREAD

**Issue by andrewmenich** [verbb/vizy#70]
**What are you trying to do?**
Provide clients with the ability to add subscript and superscript tags in their content.

**What's your proposed solution?**
tiptap provides extensions for these out of the box:

[@tiptap/extension-superscript](https://www.tiptap.dev/api/marks/superscript)
[@tiptap/extension-subscript](https://www.tiptap.dev/api/marks/subscript)

Happy to submit a PR if that's helpful. Thanks for considering!

**Comment by engram-design** [comment]
Added for the next release. To get this early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-3 as 1.0.5",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
Added in [1.0.6](https://github.com/verbb/vizy/releases/tag/1.0.6)
