### ISSUE TITLE
Add width to a block

### ISSUE THREAD

**Issue by jmchat** [verbb/vizy#71]
**What are you trying to do?**
I want to set the width of a block in the Vizy block configuration somewhere in the screenshot below
![image](https://user-images.githubusercontent.com/46917781/130461955-852213f4-5f63-419f-9ef4-71a74cca9a53.png)

You can now set a width to fields in Craft (by using the "slidepicker" as you can see above next to contentText) but you can't set it in Vizy.

**What's your proposed solution?**
Adding a slidepicker or other setting (width) field to a block would do the job. If for example the block width is 50% I want to add another block next to it. At this moment every time you want to add a new block in the editor it will start on a new line. So depending on the width of a block you can choose to add a new block on the same line or on a new line.

In this way you get more of a grid understanding in de control panel when editing a page.

**Comment by engram-design** [comment]
We probably won't be using the native column handling with Craft, because it's pretty tied to non-Vue behaviour, and how fields work.

We've got layout block types 100% on the roadmap though! https://github.com/verbb/vizy/issues/72

**Comment by jmchat** [comment]
nice 👌
