### ISSUE TITLE
Can't save in editor slideout

### ISSUE THREAD

**Issue by adrienpicard** [verbb/vizy#73]
**Description**
Edits in the new editor slideout won't save if there's a Vizy field with Blocks inside it ([console log](https://cln.sh/WyS2bn)). Saving the same entry with text-only seems to work.

**Additional info**
- Plugin version: 1.0.6
- Craft version: 3.7.10
- Multi-site: No

**Comment by engram-design** [comment]
Looks like I can replicate this, and it's due to how the delta updates work for the slide-out menu. We actually override the delta updates for Vizy fields when editing an entry (because it's not useful for the Vizy field), but there's different behaviour here. Looking into it.

**Comment by engram-design** [comment]
Should be fixed in the next release of [Craft](https://github.com/craftcms/cms/commit/ded92d19f5fb8d0e22374eb500b787f31d59bb3c)

**Comment by adrienpicard** [comment]
Ok great thanks @engram-design! I'll report back.

Somewhat related but I also noticed the "fixed" toolbar behaviour is broken in the slideout.

**Comment by engram-design** [comment]
@adrienpicard Yep, should be fixed in the latest `craft-3` branch for Vizy.

**Comment by adrienpicard** [comment]
@engram-design amazing, cheers!

**Comment by engram-design** [comment]
Fixed in [1.0.7](https://github.com/verbb/vizy/releases/tag/1.0.7) and [Craft 3.7.12](https://github.com/craftcms/cms/releases/tag/3.7.12)
