### ISSUE TITLE
Not able to query matrix field via PHP

### ISSUE THREAD

**Issue by internetztube** [verbb/vizy#8]
Primitive fields can be transformed without any problems. However, Matrix/SuperTable fields cause problems. 
In my case, I need the actual image object for the Image Slider. 
The MatrixBlockQuery of the Matrix Field returns an empty array.

<img width="1401" alt="Screenshot 2021-05-03 at 22 14 56" src="https://user-images.githubusercontent.com/6382364/116929166-581b0080-ac5e-11eb-9a9f-f8249c8f07dd.png">

```php
$result = [];
foreach ($vizyNodeCollection->all() as $node) {
    if (!($node instanceof VizyBlock)) continue; // TODO add text content transformer
    $transformedNode = ['type' => ['handle' => $node->getBlockType()['handle']]];
    /** @var FieldLayout $fieldLayout */
    $fieldLayout = $node->getFieldLayout();
    foreach ($fieldLayout->getFields() as $field) {
        $transformedNode[$field->handle] = $node->{$field->handle}->all(); // empty array
    }
    $result[] = $transformedNode;
}
var_dump($result);
```

```json
[
    {
        "type": {
            "handle": "imageGallery"
        },
        "imageGallery": []
    }
]
```

**Steps to reproduce**
1. Add Matrix Blocks (as shown in screenshot) to a Vizy Block.
2. Try to Query Matrix Blocks via PHP or Twig
3. MatrixBlockQuery returns an empty array

**Additional info**
- Plugin version: dev-master
- Craft version: Craft Pro 3.6.12
- Multi-site: **Yes**

**Comment by engram-design** [comment]
Fixed for the next release. To get the fix early, change your `verbb/vizy` requirement in `composer.json` to:

```
"require": {
  "verbb/vizy": "dev-craft-3 as 1.0.0",
  "...": "..."
}
```

Then run `composer update`.

**Comment by internetztube** [comment]
Works! Thanks!
