### ISSUE TITLE
Some rendering space issue

### ISSUE THREAD

**Issue by wmdhosting** [verbb/vizy#81]
Im on last version.. 

When i use just matrix field there is no space like on image.. 
![vizy](https://user-images.githubusercontent.com/76176291/139384723-9b465c4f-3e05-424a-ac15-253a294609df.jpg)

**Comment by engram-design** [comment]
Not really clear what you mean sorry. You mean there's spacing between Matrix blocks, which in turn are in Vizy blocks? I would've though you have full control over that in your template rendering?

What is the space exactly, is it an empty `<div>`, `<p>`, etc? Can you provide what template code you're using?

I also can't really relate the fields on the left to the preview on the right sorry. Makes it a little difficult to tell the content in the control panel vs the expected output. I'm also not familiar with the field you're using for those images/cards/stats.

**Comment by wmdhosting** [comment]
THsi space is only when i put matrix  field in Vizy.. for use in other places.. 
On other place where i use that matrix only. no spacing.. from code that is in templates..

this is div 

![2021-10-29_14-58-39](https://user-images.githubusercontent.com/76176291/139439084-cbf6c79f-d8b0-4495-9fd2-58397463e498.jpg)

**Comment by engram-design** [comment]
You've highlighted a `<div>` with the class `post-image` - that templating and style seems all your own?

**Comment by wmdhosting** [comment]
yes. templating is done  for matrix field and thats works ok. when not in Vizy field
when i put matrix in vizy field..  geting this spaces..  

And i need to use same tamplates.  for matrix field and matrix in vizy.. 

Just asked . if you hav eany idea why its happening..

**Comment by engram-design** [comment]
Hard to say without:
- Looking at your Twig templates, and how you're rendering the Vizy field and Matrix blocks
- Looking at the rendered page in dev tools to see where that CSS margin is coming from

But Vizy shouldn't impose any styles otherwise. Can you inspect the element to see where that margin is coming from?

**Comment by engram-design** [comment]
Closing due to age and need further information.
