### ISSUE TITLE
Video  embed

### ISSUE THREAD

**Issue by eduardoalonsoalbella** [verbb/vizy#83]
It would be great to have a button to embed most common video platforms, you paste a link and the video is embedded automatically.

**Comment by itsmattsoria** [comment]
Would looooove this feature; in fact, without it, I probably can't even use Vizy on certain projects. Is this being considered to be included at all?

**Comment by engram-design** [comment]
Certainly being added to our todo list, I agree it's a great feature. In fact, [tiptap](https://tiptap.dev/api/nodes/youtube) itself quite recently added an embed option for YouTube. We could implement similar, but it would need to be for a broad range of platforms, and likely not just video.

We'll likely add support for [embed](https://github.com/oscarotero/Embed) to allow you to embed anything from Tweets, SoundCloud, Vimeo, etc.

For now though, you could use an Assets field and the [embeddedassets](https://plugins.craftcms.com/embeddedassets) plugin to achieve the same functionality.

**Comment by itsmattsoria** [comment]
@engram-design yeah, I hadn't thought of that as a workaround, but could definitely work in the meantime. Thanks for responding though and I'll definitely be keeping an eye out for when that makes it in!

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0)
