### ISSUE TITLE
Add API for adding editor buttons and extending functionality with Tiptap

### ISSUE THREAD

**Issue by engram-design** [verbb/vizy#93]

**Comment by d-karstens** [comment]
Hey,

Just wanted to check if there was any update on how this one was coming along
Would be a huge help to be able to add our own typography options 👀

Cheers!

**Comment by engram-design** [comment]
No immediate progress sorry, but it'll be done by the end of the year! There's a good bunch of API work that we're scoping out.

**Comment by jasondibenedetto** [comment]
@engram-design was there any update on this one?

**Comment by engram-design** [comment]
@jasondibenedetto Actively working on it!

**Comment by engram-design** [comment]
Added in [2.1.0](https://github.com/verbb/vizy/releases/tag/2.1.0). Have a read through the [blog post](https://verbb.io/blog/vizy-2-1), the [extensibility docs](https://verbb.io/craft-plugins/vizy/docs/template-guides/extending-vizy) and the [user guides](https://verbb.io/craft-plugins/vizy/docs/user-guides)

**Comment by jasondibenedetto** [comment]
Thanks for the new release @engram-design !
