### ISSUE TITLE
Vizy Field has disappeared from content editor

### ISSUE THREAD

**Issue by danleecreates** [verbb/vizy#95]
**Description**

My vizy field has disappeared from the content editor in our live site. I can see the heading for the field but there is no text edit field underneath it. It's like there is a bug in rendering it for some reason.

- The same setup and files are working on my local copy.
- I can see the field is added to the section correctly.
- Other content items/pages/sections can not render the field.

**Additional info**
- Plugin version: 1.0.8
- Craft version: 3.7.23
- Multi-site: No

**Additional context**

<img width="459" alt="Screenshot 2022-01-17 at 2 45 24 pm" src="https://user-images.githubusercontent.com/7198242/149790528-86adae99-fa82-4cd3-bb36-2ad9d28e89e0.png">

**Comment by danleecreates** [comment]
Just an update on this. 

I upgraded to the latest versions of craft and vizy and the field is now showing again. However with a difference. My content blocks are now missing...

<img width="997" alt="Screenshot 2022-01-18 at 10 15 18 am" src="https://user-images.githubusercontent.com/7198242/149917578-438113cc-68c0-47d3-929e-e1b972a6608b.png">

<img width="495" alt="Screenshot 2022-01-18 at 10 20 06 am" src="https://user-images.githubusercontent.com/7198242/149918759-5b90476e-3f19-4a14-90a9-0532f2b306bf.png">

**Comment by engram-design** [comment]
I was going to ask if there were any JS error in your first screenshot, but as that's working again, no real use.

Looks like maybe your field's config has been corrupted? The reason you see the JSON content of the blocks is that their block type definitions are missing (your last screenshot). Are you able to look at your `fields` database table, look for the Vizy field that you're looking at, and look at the `settings` column? I'm interested if there's field layout settings in there.

Is this all on a local environment, or on a server? The settings for the field should be stored in project config, which is used when building the field and the field layout.

**Comment by engram-design** [comment]
Closing due to age.
