### ISSUE TITLE
Modal broken when inserting inline link to text in Vizy field

### ISSUE THREAD

**Issue by svale** [verbb/vizy#97]
**Description**
After upgrading Craft to version 3.7.30 the pop up modal that appears when inserting an inline link to entry is broken. 
The modal is frozen on the spinner and the javascript error in the console says: 
`Uncaught TypeError: Cannot read properties of null (reading 'html') `

This might of course be more of an an issue with Craft itself, but since it appears in the Vizy-field, I'll begin by posting it here.

The issue is resolved by downgrading to Craft 3.7.29

**Steps to reproduce**
1. Upgrade Craft to version 3.7.30 or later
2. Insert inline link via toolbar from Vizy field 

**Additional info**
- Plugin version: 1.0.9
- Craft version: 3.7.30
- Multi-site: No

**Additional context**
![image](https://user-images.githubusercontent.com/5339180/150806179-5be988a6-96cb-4832-854d-57b6af6236b0.png)

**Comment by engram-design** [comment]
Looks like an issue upstream with Craft https://github.com/craftcms/cms/issues/10428
